---
sidebar: sidebar 
permalink: concept-agent-install-options.html 
keywords: install agent, deployment method, console install, marketplace install, manual install, ova install, vcenter install, installation options, 
summary: 'Déployez un agent Console via la NetApp Console, la place de marché de votre fournisseur de cloud ou en installant manuellement le logiciel sur un hôte Linux. La méthode de déploiement choisie détermine votre niveau de contrôle sur l"hôte et la rapidité de mise en service.' 
---
= Choisissez une méthode de déploiement de l'agent Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Déployez un agent Console à l'aide de la NetApp Console, la marketplace de votre fournisseur de cloud, ou en installant manuellement le logiciel sur un hôte Linux. Votre méthode de déploiement détermine votre contrôle sur l'hôte et la rapidité avec laquelle vous pouvez commencer.

Pour les déploiements cloud, vous pouvez déployer un agent sur Amazon Web Services (AWS), Microsoft Azure ou Google Cloud.



== Déployer depuis la NetApp Console

NetApp recommande de déployer depuis la NetApp Console lorsque vous utilisez le mode standard. La NetApp Console vous guide lors de la configuration du réseau et des autorisations, puis lance automatiquement la machine virtuelle ou l'instance chez votre fournisseur de cloud. La Console vous guide lors de la configuration du réseau et des autorisations, puis lance automatiquement la machine virtuelle ou l'instance chez votre fournisseur de cloud.

Choisissez cette méthode lorsque :

* Vous effectuez un déploiement dans un environnement cloud avec accès Internet sortant.
* Vous souhaitez obtenir le chemin le plus rapide pour qu'un agent soit opérationnel, avec le moins de configuration manuelle possible.


[cols="47,47"]
|===
| Avantages | Inconvénients 


 a| 
* Configuration guidée — la Console gère la création de la machine virtuelle, l’installation du logiciel et l’enregistrement initial dans un flux de travail unique
* Applique automatiquement l'image et la configuration correctes de la machine virtuelle
* Méthode de déploiement cloud nécessitant le moins d'étapes manuelles

 a| 
* Non disponible pour les environnements sur site, en mode restreint ou isolés du réseau


|===
link:task-install-agent-aws-console.html["Déployez un agent Console dans AWS depuis la Console"] link:task-install-agent-azure-console.html["Déployez un agent Console dans Azure depuis la Console"] link:task-install-agent-google-console-gcloud.html["Déployez un agent Console dans Google Cloud depuis la Console"]



== Déployer depuis une place de marché de fournisseur de cloud

Le déploiement depuis AWS Marketplace ou Azure Marketplace lance l'installation de l'agent directement depuis la place de marché, et non depuis la NetApp Console.


NOTE: Une option équivalente à une place de marché est disponible dans Google Cloud via les outils Google Cloud (gcloud CLI ou Google Cloud console) plutôt qu'une annonce traditionnelle sur une place de marché.

Choisissez cette méthode lorsque :

* Votre organisation exige que tous les logiciels cloud soient acquis via la marketplace.
* Vous préférez lancer les déploiements depuis l'interface de votre fournisseur de cloud plutôt que depuis la NetApp Console.


[cols="47,47"]
|===
| Avantages | Inconvénients 


 a| 
* Interface de déploiement familière pour les équipes travaillant déjà dans la console du fournisseur de cloud

 a| 
* Le déploiement est lancé en dehors de la NetApp Console, le flux de travail guidé n'est donc pas disponible


|===
link:task-install-agent-aws-marketplace.html["Déployez un agent Console dans AWS depuis la marketplace"] link:task-install-agent-azure-marketplace.html["Déployez un agent de Console dans Azure à partir de la place de marché"] link:task-install-agent-google-gcloud.html["Déployez un agent de Console dans Google Cloud à l'aide des outils Google Cloud"]



== Installation manuelle sur un hôte Linux dans le cloud

L'installation manuelle vous permet d'installer le logiciel agent Console directement sur un hôte Linux que vous fournissez et gérez dans AWS, Azure, Google Cloud ou sur site.

Choisissez cette méthode lorsque :

* Vous devez effectuer le déploiement dans un environnement en mode restreint ou en mode privé sans accès Internet sortant.
* Votre organisation exige que tous les logiciels soient installés sur des hôtes pré-approuvés et gérés en interne.


[cols="47,47"]
|===
| Avantages | Inconvénients 


 a| 
* Prend en charge les environnements avec un accès Internet sortant limité (mode restreint ou mode privé)
* Les mises à jour sont gérées automatiquement lorsque l'agent de la Console a accès à Internet

 a| 
* La plupart des étapes de toute méthode de déploiement. Vous devez préparer l'hôte, installer Podman ou Docker, configurer le réseau, installer le logiciel et attribuer manuellement les permissions
* Le déploiement est lancé en dehors de la NetApp Console, le flux de travail guidé n'est donc pas disponible


|===
link:task-install-agent-aws-manual.html["Installez manuellement un agent de Console dans AWS"] link:task-install-agent-azure-manual.html["Installez manuellement un agent de Console dans Azure"] link:task-install-agent-google-manual.html["Installez manuellement un agent Console dans Google Cloud"]



== Installation manuelle sur site à l'aide de VCenter (OVA)

Si vous utilisez VMware VCenter, vous pouvez déployer l'agent Console en important un fichier OVA (Open Virtual Appliance). L'OVA est une image de machine virtuelle préconfigurée que vous déployez avec le vSphere client, sans avoir à installer Linux ni à configurer un environnement d'exécution de conteneurs.

Choisissez cette méthode lorsque :

* Vous effectuez un déploiement sur site dans un environnement VMware.
* Vous souhaitez une installation sur site plus simple, nécessitant moins de maintenance et de configuration Linux.



NOTE: Vous ne pouvez pas gérer les ressources Google Cloud depuis un agent de Console local. Pour gérer les ressources Google Cloud, installez l'agent dans Google Cloud.

[cols="47,47"]
|===
| Avantages | Inconvénients 


 a| 
* Installation sur site simplifiée, sans configuration Linux ni environnement d'exécution de conteneur requise
* Déploiement sur site uniquement ; non disponible pour les déploiements cloud
* Comprend une console de maintenance à menus pour les tâches de maintenance des agents
* Flux de travail de déploiement familier pour les administrateurs VMware
* * Une image de machine virtuelle préconfigurée contribue à prévenir les erreurs et facilite la maintenance

 a| 
* Nécessite vCenter ; ne peut pas être installé directement sur un hôte ESXi nu


|===
link:task-install-agent-on-prem-ova.html["Déployez sur site à l'aide de vCenter"]



== Installation manuelle sur site (sans vCenter)

Vous pouvez installer manuellement l'agent Console sur n'importe quel hôte Linux local. Vous devez configurer l'hôte Linux et l'environnement d'exécution de conteneurs (Docker ou Podman), puis installer l'agent Console.

Choisissez cette méthode lorsque :

* Vous effectuez un déploiement sur site et ne disposez pas d'un environnement VMware vCenter.
* Vous maîtrisez l'administration Linux et souhaitez gérer vous-même l'hôte sous-jacent.
* Vous souhaitez contrôler le moment où l'agent de la Console est mis à jour.


[cols="47,47"]
|===
| Avantages | Inconvénients 


 a| 
* Fonctionne sur tout matériel sur site ou toute plateforme VM compatible Linux — VMware n'est pas requis
* Prend en charge les déploiements en mode privé (sans connexion Internet sortante)

 a| 
* Vous devez savoir utiliser Linux et configurer Docker ou Podman vous-même
* Vous êtes responsable de l'application manuelle des mises à niveau de l'agent Console lors de la sortie de nouvelles versions


|===
link:task-install-agent-on-prem.html["Installation manuelle sur site"]
