---
sidebar: sidebar 
permalink: concept-agents.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is an agent required, agent supported locations, restricted mode, private mode, dark site, permissions, multiple agents, disaster recovery, agents, multiple agents, what is a Console agent' 
summary: Vous utilisez un agent Console pour connecter NetApp Console à votre infrastructure et orchestrer en toute sécurité des solutions de stockage sur AWS, Azure, Google Cloud ou des environnements sur site, ainsi que pour utiliser des services de protection des données. 
---
= En savoir plus sur les agents de la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous utilisez un agent Console pour connecter NetApp Console à votre infrastructure et orchestrer en toute sécurité des solutions de stockage sur AWS, Azure, Google Cloud ou des environnements sur site, ainsi que pour utiliser des services de protection des données.

Un agent Console vous permet de :

* Orchestrez les tâches de gestion du stockage depuis la NetApp Console, telles que le provisionnement de Cloud Volumes ONTAP, la configuration des volumes de stockage, l'utilisation de la classification des données, et bien plus encore.
* Authentifiez-vous à l'aide des rôles IAM de votre fournisseur de cloud pour l'intégration de la facturation des abonnements.
* Utilisez les services de données avancés (NetApp Backup and Recovery, NetApp Disaster Recovery, NetApp Ransomware Resilience et NetApp Cloud Tiering).


Si vous n'avez pas besoin de services d'orchestration avancés ou de protection des données, vous pouvez gérer de manière centralisée les clusters ONTAP sur site et les services de stockage cloud natifs sans déployer d'agent. Certains outils de surveillance et de mobilité des données sont également disponibles sans agent.

Le tableau suivant indique les fonctionnalités et services que vous pouvez utiliser avec et sans agent Console.

[cols="40,20a,20a"]
|===
|  | Disponible avec agent | Disponible sans agent 


3+| *Systèmes de stockage pris en charge* : 


| Amazon FSx pour ONTAP  a| 
Oui (fonctionnalités de découverte et de gestion)
 a| 
Oui (découverte uniquement)



| Stockage Amazon S3  a| 
Oui
 a| 
Non



| Stockage d'objets blob Azure  a| 
Oui
 a| 
Oui



| Azure NetApp Files  a| 
Oui
 a| 
Oui



| Cloud Volumes ONTAP  a| 
Oui
 a| 
Non



| Systèmes de la série E  a| 
Oui
 a| 
Non



| Google Cloud NetApp Volumes  a| 
Oui
 a| 
Oui



| compartiments de stockage Google Cloud  a| 
Oui
 a| 
Non



| Systèmes StorageGRID  a| 
Oui
 a| 
Non



| Cluster ONTAP sur site (gestion et découverte avancées)  a| 
Oui (gestion et découverte avancées)
 a| 
Non (découverte de base uniquement)



3+| *Services de gestion du stockage et de santé*: 


| Alertes  a| 
Oui
 a| 
Non



| Centre d'automatisation  a| 
Oui
 a| 
Oui



| Digital Advisor (Active IQ)  a| 
Oui
 a| 
Non



| Gestion des licences et des abonnements  a| 
Oui
 a| 
Non



| Efficacité économique  a| 
Oui
 a| 
Non



| Indicateurs du tableau de bord de la page d'accueil  a| 
Oui^2^
 a| 
Non



| Planification du cycle de vie  a| 
Oui
 a| 
Non^1^



| Durabilité  a| 
Oui
 a| 
Non



| Mises à jour logicielles  a| 
Oui
 a| 
Oui



| Charges de travail NetApp  a| 
Oui
 a| 
Oui



3+| *Services de données disponibles* : 


| NetApp Backup and Recovery  a| 
Oui
 a| 
Non



| NetApp Data Classification  a| 
Oui
 a| 
Non



| NetApp Cloud Tiering  a| 
Oui
 a| 
Non



| NetApp Copy and Sync  a| 
Oui
 a| 
Non



| NetApp Disaster Recovery  a| 
Oui
 a| 
Non



| NetApp Ransomware Resilience  a| 
Oui
 a| 
Non



| NetApp Volume Caching  a| 
Oui
 a| 
Non

|===
^1^ Vous pouvez consulter la planification du cycle de vie sans agent Console, mais un agent Console est nécessaire pour lancer des actions.

^2^ Des indicateurs précis sur la page d'accueil nécessitent des agents de console correctement dimensionnés et configurés.



== Les agents de console doivent être opérationnels à tout moment

Les agents de console sont un élément fondamental de la NetApp Console.  Il est de votre responsabilité (en tant que client) de vous assurer que les agents concernés sont opérationnels et accessibles à tout moment.  La console peut gérer de courtes pannes d'agent, mais vous devez corriger rapidement les pannes d'infrastructure.

Cette documentation est régie par le CLUF.  L'utilisation du produit en dehors de la documentation peut avoir un impact sur ses fonctionnalités et sur vos droits CLUF.



== Emplacements pris en charge

Vous pouvez installer des agents aux emplacements suivants :

* Amazon Web Services
* Microsoft Azure
+
Déployez un agent de console dans Azure dans la même région que les systèmes Cloud Volumes ONTAP qu’il gère.  Alternativement, déployez-le dans le https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Paire de régions Azure"^] .  Cela garantit qu’une connexion Azure Private Link est utilisée entre Cloud Volumes ONTAP et ses comptes de stockage associés. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-enabling-private-link.html["Découvrez comment Cloud Volumes ONTAP utilise un lien privé Azure"^]

* Google Cloud
+
Pour utiliser la console et les services de données avec Google Cloud, déployez votre agent dans Google Cloud.

* Dans vos locaux




== Communication avec les fournisseurs de cloud

L'agent utilise TLS 1.3 pour toutes les communications avec AWS, Azure et Google Cloud.



== Comment installer un agent de console

Vous pouvez installer un agent de console directement depuis la console, depuis la place de marché de votre fournisseur de cloud ou en installant manuellement le logiciel sur votre propre hôte Linux ou dans votre environnement VCenter.

* link:concept-modes.html["En savoir plus sur les modes de déploiement de la NetApp Console"]
* link:task-quick-start-standard-mode.html["Démarrer avec la NetApp Console en mode standard"]
* link:task-quick-start-restricted-mode.html["Démarrer avec la NetApp Console en mode restreint"]




== Autorisations du fournisseur de cloud

Vous avez besoin d’autorisations spécifiques pour créer l’agent de console directement à partir de la NetApp Console et d’un autre ensemble d’autorisations pour l’agent de console lui-même. Si vous créez l’agent de console dans AWS ou Azure directement à partir de la console, la console crée l’agent de console avec les autorisations dont elle a besoin.

Lorsque vous utilisez la console en mode standard, la manière dont vous fournissez les autorisations dépend de la manière dont vous prévoyez de créer l'agent de la console.

Pour savoir comment configurer les autorisations, reportez-vous à ce qui suit :

* Mode standard
+
** link:concept-install-options-aws.html["Options d'installation de l'agent dans AWS"]
** link:concept-install-options-azure.html["Options d'installation de l'agent dans Azure"]
** link:concept-install-options-google.html["Options d'installation de l'agent dans Google Cloud"]
** link:task-install-agent-on-prem.html#agent-permission-aws-azure["Configurer les autorisations cloud pour les déploiements sur site"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Configurer les autorisations pour le mode restreint"]


Pour afficher les autorisations exactes dont l'agent de la console a besoin pour les opérations quotidiennes, reportez-vous aux pages suivantes :

* link:reference-permissions-aws.html["Découvrez comment l'agent de console utilise les autorisations AWS"]
* link:reference-permissions-azure.html["Découvrez comment l'agent de console utilise les autorisations Azure"]
* link:reference-permissions-gcp.html["Découvrez comment l'agent de la console utilise les autorisations Google Cloud"]


Il est de votre responsabilité de mettre à jour les stratégies de l'agent de la console à mesure que de nouvelles autorisations sont ajoutées dans les versions ultérieures.  Les notes de publication répertorient les nouvelles autorisations.



== Mises à niveau des agents

NetApp met à jour le logiciel de l'agent tous les mois pour ajouter des fonctionnalités et améliorer la stabilité.  Certaines fonctionnalités de la console, telles que Cloud Volumes ONTAP et la gestion des clusters ONTAP sur site, dépendent de la version et des paramètres de l'agent de la console.

Lorsque vous installez votre agent dans le cloud, l'agent Console se met à jour automatiquement s'il dispose d'un accès Internet.



== Maintenance du système d'exploitation et des machines virtuelles

La maintenance du système d'exploitation sur l'hôte de l'agent de console est votre responsabilité (celle du client).  Par exemple, vous (client) devez appliquer les mises à jour de sécurité au système d'exploitation sur l'hôte de l'agent de console en suivant les procédures standard de votre entreprise pour la distribution du système d'exploitation.

Notez que vous (client) n'avez pas besoin d'arrêter les services sur l'hôte Console gent lors de l'application de mises à jour de sécurité mineures.

Si vous (client) devez arrêter puis démarrer la machine virtuelle de l'agent de console, vous devez le faire à partir de la console de votre fournisseur de cloud ou en utilisant les procédures standard de gestion sur site.

<<agents-must-be-operational-at-all-times,L'agent de la console doit être opérationnel à tout moment>> .



== Systèmes et agents multiples

Un agent peut gérer plusieurs systèmes et prendre en charge les services de données dans la console.  Vous pouvez utiliser un seul agent pour gérer plusieurs systèmes en fonction de la taille du déploiement et des services de données que vous utilisez.

Pour les déploiements à grande échelle, travaillez avec votre représentant NetApp pour dimensionner votre environnement.  Contactez le support NetApp si vous rencontrez des problèmes.

Voici quelques exemples de déploiements d’agents :

* Vous disposez d'un environnement multicloud (par exemple, AWS et Azure) et vous préférez avoir un agent dans AWS et un autre dans Azure.  Chacun gère les systèmes Cloud Volumes ONTAP exécutés dans ces environnements.
* Un fournisseur de services peut utiliser une organisation de console pour fournir des services à ses clients, tout en utilisant une autre organisation pour assurer la reprise après sinistre de l'une de ses unités commerciales.  Chaque organisation a besoin de son propre agent.

