---
sidebar: sidebar 
permalink: reference-permissions-gcp.html 
keywords: permissions, gcp, gcp permissions, bluexp, console agent 
summary: 'L"agent de console nécessite des autorisations pour effectuer des actions chez votre fournisseur de cloud.  Ces autorisations sont incluses dans les politiques fournies par NetApp.  Vous devez comprendre ce que l’agent fait avec ces autorisations.' 
---
= Autorisations Google Cloud pour l'agent de la console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'agent de la console nécessite des autorisations pour effectuer des actions dans Google Cloud. Ces autorisations sont incluses dans un rôle personnalisé fourni par NetApp. Vous devez comprendre ce que l’agent fait avec ces autorisations.



== Autorisations du compte utilisateur Google Cloud

Le rôle personnalisé ci-dessous confère à un utilisateur Google Cloud les autorisations nécessaires pour déployer un agent.  Attribuez ce rôle personnalisé à l'utilisateur qui déploiera l'agent.

.Afficher les autorisations du compte utilisateur Google Cloud
[%collapsible]
====
[source, yaml]
----
title: Console agent deployment policy
description: Permissions for the user who deploys the Console agent
stage: GA
includedPermissions:

- cloudbuild.builds.get
- compute.disks.create
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.get
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.updateDisplayDevice
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.networks.updatePolicy
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.subnetworks.get
- compute.subnetworks.list
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- config.deployments.create
- config.operations.get
- config.deployments.delete
- config.deployments.deleteState
- config.deployments.get
- config.deployments.getState
- config.deployments.list
- config.deployments.update
- config.deployments.updateState
- config.previews.get
- config.previews.list
- config.revisions.get
- config.resources.list
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- resourcemanager.projects.get
- compute.instances.setServiceAccount
- iam.serviceAccounts.actAs
- iam.serviceAccounts.create
- iam.serviceAccounts.list
- iam.serviceAccountKeys.create
- storage.buckets.create
- storage.buckets.get
- storage.objects.create
- storage.folders.create
- storage.objects.list

----
====


== Autorisations du compte de service

Le rôle personnalisé ci-dessous confère au compte de service Google Cloud associé à l'agent Console les autorisations nécessaires pour gérer les ressources et les processus de votre réseau Google Cloud.

Appliquez ce rôle personnalisé à un compte de service associé à la machine virtuelle de l'agent de console.

* link:task-install-agent-google-console-gcloud.html#agent-permissions-google["Configurer les autorisations Google Cloud pour le mode standard"]
* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Configurer les autorisations pour le mode restreint"]


.Afficher les autorisations du compte de service Google
[%collapsible]
====
Veillez à ce que le rôle soit à jour, car de nouvelles autorisations sont ajoutées ou supprimées dans les versions ultérieures.  Le journal des modifications répertorie toutes les nouvelles autorisations requises.link:reference-permissions-gcp.html#gcp-permissions-change-log["Consultez le journal des modifications des autorisations Google"] link:task-adding-gcp-accounts.html["Consultez la procédure pour ajouter des comptes de service Google Cloud."]

[source, yaml]
----
title: NetApp Console agent
description: Permissions for the service account associated with the Console agent.
stage: GA
includedPermissions:
- cloudbuild.builds.get
- cloudbuild.connections.list
- cloudbuild.repositories.accessReadToken
- cloudbuild.repositories.list
- cloudquotas.quotas.get
- cloudkms.cryptoKeys.getIamPolicy
- cloudkms.cryptoKeys.setIamPolicy
- cloudkms.keyRings.get
- cloudkms.keyRings.getIamPolicy
- cloudkms.keyRings.setIamPolicy
- config.artifacts.import
- config.deployments.create
- config.deployments.delete
- config.deployments.deleteState
- config.deployments.get
- config.deployments.getLock
- config.deployments.getState
- config.deployments.update
- config.deployments.updateState
- config.previews.upload
- config.revisions.get
- config.revisions.getState
- config.deployments.getLock
- config.deployments.list
- config.deployments.lock
- config.operations.get
- config.previews.get
- config.previews.list
- config.resources.list
- compute.regionBackendServices.create
- compute.regionBackendServices.get
- compute.regionBackendServices.list
- compute.regionBackendServices.update
- compute.networks.updatePolicy
- compute.addresses.createInternal
- compute.addresses.deleteInternal
- compute.addresses.list
- compute.addresses.setLabels
- compute.addresses.useInternal
- compute.backendServices.create
- compute.disks.create
- compute.disks.createSnapshot
- compute.disks.delete
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.forwardingRules.create
- compute.forwardingRules.delete
- compute.forwardingRules.get
- compute.forwardingRules.setLabels
- compute.globalOperations.get
- compute.healthChecks.create
- compute.healthChecks.delete
- compute.healthChecks.get
- compute.healthChecks.useReadOnly
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.addAccessConfig
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.delete
- compute.instances.detachDisk
- compute.instances.get
- compute.instances.getSerialPortOutput
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.stop
- compute.instances.updateDisplayDevice
- compute.instances.use
- compute.instanceGroups.create
- compute.instanceGroups.delete
- compute.instanceGroups.get
- compute.instanceGroups.update
- compute.instanceGroups.use
- compute.addresses.get
- compute.instances.updateNetworkInterface
- compute.instances.setMinCpuPlatform
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.regionBackendServices.delete
- compute.regionBackendServices.use
- compute.resourcePolicies.create
- compute.resourcePolicies.delete
- compute.resourcePolicies.get
- compute.snapshots.create
- compute.snapshots.delete
- compute.snapshots.get
- compute.snapshots.list
- compute.snapshots.setLabels
- compute.subnetworks.get
- compute.subnetworks.list
- compute.subnetworks.use
- compute.subnetworks.useExternalIp
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- compute.instances.setServiceAccount
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- logging.logEntries.list
- logging.privateLogEntries.list
- logging.logEntries.create
- logging.logEntries.route
- monitoring.timeSeries.list
- resourcemanager.projects.get
- storage.buckets.create
- storage.buckets.delete
- storage.buckets.get
- storage.buckets.list
- storage.objects.create
- storage.objects.delete
- storage.objects.update
- cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
- storage.buckets.update
- iam.serviceAccounts.actAs
- iam.serviceAccounts.create
- iam.serviceAccounts.get
- iam.serviceAccounts.getIamPolicy
- iam.serviceAccounts.list
- iam.serviceAccountKeys.create
- storage.objects.get
- storage.buckets.getIamPolicy



----
====


== Comment les autorisations Google Cloud sont utilisées

L'agent Console utilise les autorisations du rôle personnalisé pour gérer les ressources Cloud Volumes ONTAP et les processus de services de données NetApp sur votre réseau Google Cloud.  Les sections suivantes décrivent comment l'agent utilise ces autorisations.



=== Autorisations utilisées pour Cloud Volumes ONTAP

L'agent Console utilise les autorisations du rôle personnalisé pour gérer les ressources et les processus Cloud Volumes ONTAP de votre réseau Google Cloud.  Les sections suivantes décrivent comment l'agent utilise ces autorisations.

.Autorisations pour Cloud Volumes ONTAP
[%collapsible]
====
[cols="5*"]
|===
| Actions | But | Utilisé pour le déploiement ? | Utilisé pour les opérations quotidiennes ? | Utilisé pour la suppression ? 


| config.déploiements.créer .15+| Pour déployer l'instance de machine virtuelle Cloud Volumes ONTAP à l'aide de Google Cloud Infrastructure Manager. | Oui | Non | Non 


| config.deployments.delete | Non | Non | Oui 


| config.deployments.deleteState | Non | Non | Oui 


| config.deployments.get | Non | Oui | Non 


| config.deployments.getLock | Non | Oui | Non 


| config.deployments.getState | Non | Oui | Non 


| config.déploiements.liste | Non | Oui | Non 


| config.déploiements.lock | Non | Oui | Non 


| config.déploiements.mise à jour | Non | Oui | Non 


| config.deployments.updateState | Non | Oui | Non 


| config.operations.get | Non | Oui | Non 


| config.previews.get | Non | Oui | Non 


| config.previews.list | Non | Oui | Non 


| config.resources.list | Non | Oui | Non 


| config.revisions.get | Non | Oui | Non 


| calculer.disques.créer .7+| Pour créer et gérer des disques pour Cloud Volumes ONTAP. | Oui | Oui | Non 


| calculer.disques.créerSnapshot | Non | Oui | Non 


| supprimer.disques.calculer | Non | Oui | Oui 


| calculer.disques.obtenir | Non | Oui | Non 


| liste des disques de calcul | Oui | Oui | Non 


| calculer.disques.setLabels | Oui | Oui | Non 


| calculer.disques.utiliser | Non | Oui | Non 


| calculer.firewalls.create .4+| Pour créer des règles de pare-feu pour Cloud Volumes ONTAP. | Oui | Non | Non 


| calculer.firewalls.delete | Non | Oui | Oui 


| calculer.firewalls.get | Oui | Oui | Non 


| liste des pare-feu | Oui | Oui | Non 


| calculer.forwardingRules.créer | Créez des règles de transfert pour le routage du trafic vers les services backend. | Non | Oui | Non 


| calculer.forwardingRules.delete | Supprimer les règles de transfert existantes. | Non | Oui | Non 


| calculer.forwardingRules.get | Récupérer les détails des règles de redirection existantes. | Non | Oui | Non 


| calculer.forwardingRules.setLabels | Définir ou mettre à jour les étiquettes des règles de transfert pour l'organisation. | Non | Oui | Non 


| calculer.globalOperations.get | Pour obtenir l'état des opérations. | Oui | Oui | Non 


| calculer.healthChecks.créer .4+| Créer et gérer des contrôles d'intégrité pour surveiller l'état des services backend. | Non | Oui | Non 


| calculer.healthChecks.supprimer | Non | Oui | Non 


| calculer.healthChecks.get | Non | Oui | Non 


| calculer.healthChecks.useReadOnly | Non | Oui | Non 


| calculer.images.obtenir .4+| Pour obtenir des images pour les instances de VM. | Oui | Non | Non 


| calculer.images.getFromFamily | Oui | Non | Non 


| calculer.images.liste | Oui | Non | Non 


| calculer.images.utiliserLectureSeule | Oui | Non | Non 


| calculer.instances.attacherDisque .2+| Pour attacher et détacher des disques à Cloud Volumes ONTAP. | Oui | Oui | Non 


| calculer.instances.détacherDisque | Non | Oui | Oui 


| calculer.instances.créer .2+| Pour créer et supprimer des instances de machine virtuelle Cloud Volumes ONTAP . | Oui | Non | Non 


| calculer.instances.supprimer | Non | Non | Oui 


| calculer.instances.get | Pour répertorier les instances de VM. | Oui | Oui | Non 


| compute.instances.getSerialPortOutput | Pour obtenir les journaux de la console. | Oui | Oui | Non 


| liste des instances de calcul | Pour récupérer la liste des instances dans une zone. | Oui | Oui | Non 


| calculer.instances.setDeletionProtection | Pour définir la protection contre la suppression sur l'instance. | Oui | Non | Non 


| calculer.instances.setLabels | Pour ajouter des étiquettes. | Oui | Non | Non 


| compute.instances.setMachineType .2+| Pour modifier le type de machine pour Cloud Volumes ONTAP. | Oui | Oui | Non 


| compute.instances.setMinCpuPlatform | Oui | Oui | Non 


| compute.instances.setMetadata | Pour ajouter des métadonnées. | Oui | Oui | Non 


| calculer.instances.setTags | Pour ajouter des balises pour les règles de pare-feu. | Oui | Oui | Non 


| calculer.instances.démarrer .3+| Pour démarrer et arrêter Cloud Volumes ONTAP. | Oui | Oui | Non 


| calculer.instances.stop | Oui | Oui | Non 


| calculer.instances.updateDisplayDevice | Oui | Oui | Non 


| calculer.instances.utiliser | Utiliser des instances de machines virtuelles (opérations de démarrage, d'arrêt et de connexion). | Non | Oui | Non 


| calculer.machineTypes.get | Pour obtenir le nombre de cœurs afin de vérifier les quotas. | Oui | Non | Non 


| calculer.projets.obtenir | Pour soutenir des projets multiples. | Oui | Non | Non 


| calculer.resourcePolicies.créer .3+| Créer et gérer des politiques de ressources pour la gestion automatisée des ressources. | Non | Oui | Non 


| calculer.resourcePolicies.supprimer | Non | Oui | Non 


| calculer.resourcePolicies.get | Non | Oui | Non 


| calculer.instantanés.créer .5+| Pour créer et gérer des instantanés de disque persistants. | Oui | Oui | Non 


| calculer.instantanés.supprimer | Non | Oui | Oui 


| calculer.instantanés.obtenir | Non | Oui | Non 


| liste des instantanés de calcul | Non | Oui | Non 


| calculer.instantanés.setLabels | Oui | Oui | Non 


| calculer.réseaux.obtenir .9+| Pour obtenir les informations réseau nécessaires à la création d'une nouvelle instance de machine virtuelle Cloud Volumes ONTAP . | Oui | Oui | Non 


| liste des réseaux de calcul | Oui | Oui | Non 


| calculer.régions.obtenir | Oui | Oui | Non 


| calculer.régions.liste | Oui | Oui | Non 


| calculer.sous-réseaux.obtenir | Oui | Oui | Non 


| liste des sous-réseaux | Oui | Oui | Non 


| calculer.zoneOperations.get | Oui | Oui | Non 


| calculer.zones.obtenir | Oui | Oui | Non 


| liste des zones de calcul | Oui | Oui | Non 


| deploymentmanager.compositeTypes.get .16+| Pour déployer l’instance de machine virtuelle Cloud Volumes ONTAP à l’aide de Google Cloud Deployment Manager. | Oui | Non | Non 


| deploymentmanager.compositeTypes.list | Oui | Non | Non 


| deploymentmanager.deployments.create | Oui | Non | Non 


| deploymentmanager.deployments.delete | Oui | Non | Non 


| deploymentmanager.deployments.get | Oui | Non | Non 


| gestionnaire de déploiement.déploiements.liste | Oui | Non | Non 


| deploymentmanager.manifests.get | Oui | Non | Non 


| deploymentmanager.manifests.list | Oui | Non | Non 


| deploymentmanager.operations.get | Oui | Non | Non 


| deploymentmanager.operations.list | Oui | Non | Non 


| deploymentmanager.resources.get | Oui | Non | Non 


| deploymentmanager.resources.list | Oui | Non | Non 


| deploymentmanager.typeProviders.get | Oui | Non | Non 


| deploymentmanager.typeFournisseurs.liste | Oui | Non | Non 


| deploymentmanager.types.get | Oui | Non | Non 


| deploymentmanager.types.list | Oui | Non | Non 


| logging.logEntries.list .2+| Pour obtenir les lecteurs de journaux de pile. | Oui | Oui | Non 


| logging.privateLogEntries.list | Oui | Oui | Non 


| logging.logEntries.create .2+| Créer et acheminer les entrées de journal à des fins de surveillance, de débogage et d'audit. | Oui | Oui | Non 


| logging.logEntries.route | Oui | Oui | Non 


| resourcemanager.projects.get | Pour soutenir des projets multiples. | Oui | Oui | Non 


| storage.buckets.create .5+| Pour créer et gérer un bucket Google Cloud Storage pour la hiérarchisation des données. | Oui | Oui | Non 


| suppression des buckets de stockage | Non | Oui | Oui 


| storage.buckets.get | Non | Oui | Non 


| liste des compartiments de stockage | Non | Oui | Non 


| mise à jour des buckets de stockage | Non | Oui | Non 


| cloudkms.cryptoKeyVersions.useToEncrypt .5+| Pour utiliser les clés de chiffrement gérées par le client à partir du service Cloud Key Management avec Cloud Volumes ONTAP. | Oui | Oui | Non 


| cloudkms.cryptoKeys.get | Oui | Oui | Non 


| cloudkms.cryptoKeys.list | Oui | Oui | Non 


| cloudkms.keyRings.list | Oui | Oui | Non 


| cloudbuild.builds.get | Oui | Non | Non 


| compute.instances.setServiceAccount .6+| Pour définir un compte de service sur l’instance Cloud Volumes ONTAP .  Ce compte de service fournit des autorisations pour la hiérarchisation des données vers un bucket Google Cloud Storage. | Oui | Oui | Non 


| je suis.comptesdeservice.agirEnTantQue | Oui | Non | Non 


| je suis.comptesdeservice.créer | Oui | Non | Non 


| iam.serviceAccounts.getIamPolicy | Oui | Oui | Non 


| liste des comptes de service iam | Oui | Oui | Non 


| iam.serviceAccountKeys.create | Oui | Non | Non 


| création d'objets de stockage .4+| Créez et gérez des objets (fichiers) dans un bucket Google Cloud Storage. | Oui | Oui | Non 


| suppression des objets de stockage | Non | Non | Oui 


| storage.objects.get | Oui | Oui | Non 


| liste des objets de stockage | Oui | Oui | Non 


| liste des adresses calculées | Pour récupérer les adresses dans une région lors du déploiement d'une paire HA. | Oui | Non | Non 


| calculer.adresses.créerInterne | Créer des adresses IP internes au sein du réseau VPC pour l'allocation des ressources. | Non | Oui | Non 


| calculer.adresses.supprimerInterne | Suppression des adresses IP internes pour le nettoyage des ressources. | Non | Oui | Non 


| calculer.adresses.setLabels | Mettre à jour les étiquettes de la ressource Adresse. | Non | Oui | Non 


| calculer.adresses.utiliserInterne | Utilisez les adresses IP internes pour les communications réseau. | Non | Oui | Non 


| calculer.backendServices.créer | Pour configurer un service backend pour distribuer le trafic dans une paire HA. | Oui | Non | Non 


| calculer.regionBackendServices.créer .6+| Créer et gérer les services backend pour le routage du trafic. | Oui | Non | Non 


| compute.regionBackendServices.delete | Non | Oui | Non 


| compute.regionBackendServices.get | Oui | Non | Non 


| calculer.regionBackendServices.update | Oui | Oui | Non 


| compute.regionBackendServices.list | Oui | Non | Non 


| compute.regionBackendServices.use | Non | Oui | Non 


| compute.networks.updatePolicy | Pour appliquer des règles de pare-feu sur les VPC et les sous-réseaux pour une paire HA. | Oui | Non | Non 


| calculer.instanceGroups.get .7+| Pour créer et gérer des machines virtuelles de stockage sur des paires Cloud Volumes ONTAP HA. | Oui | Oui | Non 


| calculer.adresses.obtenir | Oui | Oui | Non 


| compute.instances.updateNetworkInterface | Oui | Oui | Non 


| calculer.instanceGroups.créer | Non | Oui | Non 


| calculer.instanceGroups.supprimer | Non | Oui | Non 


| calculer.instanceGroups.update | Non | Oui | Non 


| calculer.instanceGroups.utiliser | Non | Oui | Non 


| monitoring.timeSeries.list .2+| Pour découvrir des informations sur les buckets Google Cloud Storage. | Oui | Oui | Non 


| storage.buckets.getIamPolicy | Oui | Oui | Non 
|===
====


=== Autorisations utilisées pour NetApp Backup and Recovery

L'agent de la console utilise les autorisations du rôle personnalisé pour gérer les ressources et les processus NetApp Backup and Recovery sur votre réseau Google Cloud.  Les sections suivantes décrivent comment l'agent utilise ces autorisations.

.Afficher les autorisations pour NetApp Backup and Recovery
[%collapsible]
====
[cols="5*"]
|===


| Actions | But | Utilisé pour le déploiement ? | Utilisé pour les opérations quotidiennes ? | Utilisé pour la suppression ? 


 a| 
* cloudkms.cryptoKeys.get
* cloudkms.cryptoKeys.getIamPolicy
* cloudkms.cryptoKeys.list
* cloudkms.cryptoKeys.setIamPolicy
* cloudkms.porte-clés.get
* cloudkms.keyRings.getIamPolicy
* cloudkms.keyRings.list
* cloudkms.keyRings.setIamPolicy

| Pour sélectionner vos propres clés gérées par le client dans l'assistant d'activation de NetApp Backup and Recovery au lieu d'utiliser les clés de chiffrement par défaut gérées par Google. | Oui | Oui | Non 
|===
====


=== Autorisations utilisées pour la NetApp Data Classification

L'agent de la console utilise les autorisations du rôle personnalisé pour gérer les ressources et les processus de NetApp Data Classification sur votre réseau Google Cloud.  Les sections suivantes décrivent comment l'agent utilise ces autorisations.

.Autorisations d'affichage pour la NetApp Data Classification
[%collapsible]
====
[cols="5*"]
|===


| Actions | But | Utilisé pour le déploiement ? | Utilisé pour les opérations quotidiennes ? | Utilisé pour la suppression ? 


 a| 
* calculer.sous-réseaux.utiliser
* calculer.subnetworks.useExternalIp
* compute.instances.addAccessConfig

| Pour activer la NetApp Data Classification. | Oui | Non | Non 
|===
====


== Journal des modifications

Les autorisations ajoutées et supprimées sont indiquées ci-dessous.



=== 8 décembre 2025

NetApp passe de Google Cloud Deployment Manager à Google Cloud Infrastructure Manager (IM) pour déployer et exécuter l'agent Console dans Google Cloud.  Les autorisations suivantes ont été ajoutées pour prendre en charge cette modification.

Les autorisations supplémentaires suivantes sont requises pour l'utilisateur Google Cloud qui déploie l'agent :

* storage.buckets.create
* storage.buckets.get
* création d'objets de stockage
* storage.folders.create
* liste des objets de stockage
* je suis.compte_de_service.agir_en
* config.déploiements.créer
* config.operations.get


Les autorisations supplémentaires suivantes sont requises pour le compte de service Google Cloud utilisé pour les opérations quotidiennes :

* cloudbuild.connections.list
* cloudbuild.repositories.accessReadToken
* cloudbuild.repositories.list
* cloudquotas.quotas.get
* config.artifacts.import
* config.deployments.deleteState
* config.deployments.getLock
* config.deployments.getState
* config.deployments.updateState
* config.previews.upload
* config.revisions.getState
* logging.logEntries.create
* création d'objets de stockage
* suppression des objets de stockage
* mise à jour des objets de stockage
* iam.serviceAccounts.get


Les autorisations supplémentaires suivantes sont requises pour déployer Cloud Volumes ONTAP:

* cloudbuild.builds.get
* config.deployments.delete
* config.deployments.deleteState
* config.deployments.get
* config.deployments.getState
* config.déploiements.liste
* config.déploiements.mise à jour
* config.deployments.updateState
* config.previews.get
* config.previews.list
* config.revisions.get
* config.resources.list
* iam.serviceAccountKeys.create
* je suis.comptesdeservice.créer


Les autorisations supplémentaires suivantes sont requises pour le compte de service utilisé pour les opérations quotidiennes de Cloud Volumes ONTAP.

* calculer.adresses.créerInterne
* calculer.adresses.supprimerInterne
* calculer.adresses.setLabels
* calculer.adresses.utiliserInterne
* calculer.forwardingRules.créer
* calculer.forwardingRules.delete
* calculer.forwardingRules.get
* calculer.forwardingRules.setLabels
* calculer.healthChecks.créer
* calculer.healthChecks.supprimer
* calculer.healthChecks.get
* calculer.healthChecks.useReadOnly
* calculer.instanceGroups.créer
* calculer.instanceGroups.supprimer
* calculer.instanceGroups.update
* calculer.instanceGroups.utiliser
* calculer.instances.utiliser
* compute.regionBackendServices.delete
* calculer.regionBackendServices.update
* compute.regionBackendServices.use
* calculer.resourcePolicies.créer
* calculer.resourcePolicies.supprimer
* calculer.resourcePolicies.get
* logging.logEntries.route
* config.déploiements.créer
* config.deployments.delete
* config.deployments.get
* config.déploiements.mise à jour
* config.revisions.get
* config.déploiements.lock
* config.operations.get




=== 26 novembre 2025

Les autorisations ont été mises à jour afin de clarifier leur utilisation, mais aucune autorisation n'a été ajoutée ni supprimée. Trois colonnes ont été ajoutées pour indiquer si chaque autorisation est utilisée pour le déploiement, les opérations quotidiennes ou la suppression. En outre, certaines autorisations sont segmentées en fonction de leur utilisation pour la NetApp Data Classification et la NetApp Backup and Recovery.



=== 06 février 2023

L'autorisation suivante a été ajoutée à cette politique :

* compute.instances.updateNetworkInterface


Cette autorisation est requise pour Cloud Volumes ONTAP.



=== 27/01/2023

Les autorisations suivantes ont été ajoutées à cette politique :

* cloudkms.cryptoKeys.getIamPolicy
* cloudkms.cryptoKeys.setIamPolicy
* cloudkms.porte-clés.get
* cloudkms.keyRings.getIamPolicy
* cloudkms.keyRings.setIamPolicy


Ces autorisations sont requises pour NetApp Backup and Recovery.
