---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, BlueXP, Cloud Volumes ONTAP, days, running, Connectors should remain running, imdsv2, https tokens, agents should remain running, Console agent 
summary: 'Les limitations connues identifient les plates-formes, les appareils ou les fonctions qui ne sont pas pris en charge par cette version du produit ou qui n"interagissent pas correctement avec elle. Examinez attentivement ces limitations.' 
---
= Limitations connues de la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plates-formes, les appareils ou les fonctions qui ne sont pas pris en charge par cette version du produit ou qui n'interagissent pas correctement avec elle. Examinez attentivement ces limitations.

Ces limitations sont spécifiques à la configuration de la console NEtApp et à l'administration : l'agent, la plateforme SaaS (logiciel en tant que service), etc.



== Limitations de l'agent de console



=== Conflit possible avec les adresses IP dans la plage 172

La NetApp Console déploie un agent avec deux interfaces dont les adresses IP sont comprises dans les plages 172.17.0.0/16 et 172.18.0.0/16.

Si votre réseau dispose d’un sous-réseau configuré avec l’une de ces plages, vous risquez de rencontrer des échecs de connectivité depuis la console.  Par exemple, la découverte de clusters ONTAP sur site dans la console peut échouer.

Voir l'article de la base de connaissanceslink:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/Cloud_Manager_shows_inactive_as_Connector_IP_range_in_172.x.x.x_conflict_with_docker_network["Conflit IP de l'agent avec le réseau existant"] pour obtenir des instructions sur la façon de modifier l'adresse IP des interfaces de l'agent.



=== Le décryptage SSL n'est pas pris en charge

La console ne prend pas en charge les configurations de pare-feu pour lesquelles le décryptage SSL est activé.  Si le décryptage SSL est activé, des messages d'erreur s'affichent dans la console et l'instance de l'agent s'affiche comme inactive.

Pour une sécurité renforcée, vous avez la possibilité delink:task-installing-https-cert.html["installer un certificat HTTPS signé par une autorité de certification (CA)"] .



=== Page blanche lors du chargement de l'interface utilisateur locale

Si vous chargez la console Web exécutée sur un agent, l'interface peut parfois ne pas s'afficher et vous obtenez simplement une page vierge.

Ce problème est lié à un problème de mise en cache.  La solution de contournement consiste à utiliser une session de navigateur Web privée ou en mode navigation privée.



=== Les hôtes Linux partagés ne sont pas pris en charge

L'agent n'est pas pris en charge sur une machine virtuelle partagée avec d'autres applications.  La VM doit être dédiée au logiciel agent.



=== Agents et extensions tiers

Les agents tiers ou les extensions de machine virtuelle ne sont pas pris en charge sur la machine virtuelle de l'agent.
