---
sidebar: sidebar 
permalink: reference-ports-gcp.html 
keywords: ports, firewall rules, http, https, inbound, outbound, connector, agent 
summary: 'Les règles de pare-feu Google Cloud pour l"agent nécessitent des règles entrantes et sortantes.  La NetApp Console crée automatiquement ce groupe de sécurité lorsque vous créez un agent de console à partir de la console. Pour les autres options d"installation, vous devez configurer ce groupe de sécurité manuellement.' 
---
= Règles de pare-feu d'agent dans Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les règles de pare-feu Google Cloud pour l'agent nécessitent des règles entrantes et sortantes.  La NetApp Console crée automatiquement ce groupe de sécurité lorsque vous créez un agent de console à partir de la console. Pour les autres options d'installation, vous devez configurer ce groupe de sécurité manuellement.



== Règles entrantes

[cols="10,10,80"]
|===
| Protocole | Port | But 


| SSH | 22 | Fournit un accès SSH à l'hôte de l'agent 


| HTTP | 80  a| 
* Fournit un accès HTTP depuis les navigateurs Web clients vers l'interface utilisateur locale
* Utilisé pendant le processus de mise à niveau de Cloud Volumes ONTAP




| HTTPS | 443 | Fournit un accès HTTPS depuis les navigateurs Web clients vers l'interface utilisateur locale 


| TCP | 3128 | Fournit à Cloud Volumes ONTAP un accès Internet.  Vous devez ouvrir manuellement ce port après le déploiement. 
|===


== Règles de sortie

Les règles de pare-feu prédéfinies de l'agent ouvrent tout le trafic sortant.  Suivez les règles sortantes de base si elles sont acceptables, ou utilisez des règles sortantes avancées pour des exigences plus strictes.



=== Règles de base pour les voyages sortants

Les règles de pare-feu prédéfinies pour l'agent incluent les règles sortantes suivantes.

[cols="20,20,60"]
|===
| Protocole | Port | But 


| Tous les TCP | Tous | Tout le trafic sortant 


| Tout UDP | Tous | Tout le trafic sortant 
|===


=== Règles sortantes avancées

Si vous avez besoin de règles strictes pour le trafic sortant, vous pouvez utiliser les informations suivantes pour ouvrir uniquement les ports requis pour la communication sortante par l'agent.


NOTE: L'adresse IP source est l'hôte de l'agent.

[cols="5*"]
|===
| Service | Protocole | Port | Destination | But 


| Appels API et AutoSupport | HTTPS | 443 | Gestion de cluster Internet sortant et ONTAP LIF | Appels d'API vers Google Cloud, vers ONTAP, vers NetApp Data Classification et envoi de messages AutoSupport à NetApp 


| Appels d'API | TCP | 8080 | Classification des données | Sonder l'instance de classification des données pendant le déploiement 


| DNS | UDP | 53 | DNS | Utilisé pour la résolution DNS par classification des données 
|===