---
sidebar: sidebar 
permalink: reference-networking-saas-console-previous.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, netapp console 
summary: Vous devez vous assurer que la console et tous les agents que vous installez disposent du bon accès réseau pour fonctionner correctement. 
---
= Accès réseau pour NetApp Console 3.9.55 et versions antérieures
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La NetApp Console, l'agent de la NetApp Console et les services de données NetApp nécessitent un accès Internet sortant pour contacter les points de terminaison nécessaires.


NOTE: Cette rubrique documente l'accès réseau requis pour les versions du mode standard de la NetApp Console 3.9.55 et inférieures.  Pour les points de terminaison requis pour la version 4.0.0 et supérieure, consultezlink:reference-networking-saas-console.html["les points de terminaison requis pour la version 4.0.0 et supérieure"] .

Vous devez configurer l’accès au réseau pour les éléments suivants :

* Ordinateurs qui accèdent à la NetApp Console en tant que logiciel en tant que service (SaaS)
* Agents de console que vous installez sur site ou dans le cloud.




== Mettez à jour votre liste de points de terminaison vers la liste révisée pour la version 4.0.0 et supérieure

À partir de la version 4.0.0, les agents de console nécessitent moins de points de terminaison.  Les déploiements existants avant la version 4.0.0 restent pris en charge.  Après la mise à niveau vers la version 4.0.0 ou une version ultérieure, vous pouvez supprimer les anciens points de terminaison de votre liste d'autorisation lorsque cela vous convient.

NetApp recommande de mettre à jour les règles de pare-feu pour utiliser la liste de points de terminaison révisée, qui est plus petite, plus sécurisée et plus facile à gérer.  NetApp supprime le besoin d'entrées génériques et les points de terminaison pour les mises à niveau des agents prennent en charge tous les services de données.

[cols="3*"]
|===
| *Points de terminaison pour la version 3.9.55 et les versions antérieures* | *Points de terminaison pour 4.0.0 et versions ultérieures* | *But* 


 a| 
* \ https://support.netapp.com
* \ https://mysupport.netapp.com

 a| 
* \ https://mysupport.netapp.com
* \ https://signin.b2c.netapp.com
* \ https://support.netapp.com

 a| 
Pour obtenir une licence et contacter le support NetApp .



 a| 
* \https://*.api.bluexp.netapp.com
* \ https://api.bluexp.netapp.com
* \https://*.cloudmanager.cloud.netapp.com
* \ https://cloudmanager.cloud.netapp.com
* \ https://netapp-cloud-account.auth0.com
* \ https://netapp-cloud-account.us.auth0.com
* \ https://console.netapp.com
* \https://*.console.netapp.com

 a| 
* \ https://api.bluexp.netapp.com
* \ https://netapp-cloud-account.auth0.com
* \ https://netapp-cloud-account.us.auth0.com
* \ https://console.netapp.com
* \https://components.console.netapp.com
* \ https://cdn.auth0.com

 a| 
Pour les opérations quotidiennes.



 a| 
* \https://*.blob.core.windows.net
* \ https://cloudmanagerinfraprod.azurecr.io

 a| 
* \ https://bluexpinfraprod.eastus2.data.azurecr.io
* \ https://bluexpinfraprod.azurecr.io

| Pour obtenir des images pour les mises à niveau de l'agent de console. 
|===
.Étapes
. Vérifiez que votre agent est en version 4.0.0 ou supérieure.link:task-troubleshoot-agent.html#view-the-console-agent-version["Afficher la version de l'agent."]
. Mettre sur liste blanche les points de terminaison danslink:reference-networking-saas-console.html["Points de terminaison pris en charge pour la version 4.0.0 et supérieure"] .
. Redémarrez le service Service Manager 2 sur chaque agent en exécutant la commande suivante :
+
[source, cli]
----
systemctl restart netapp-service-manager.service
----
. Exécutez la commande suivante et vérifiez que l'état de l'agent indique _actif (en cours d'exécution)_ : _
+
[source, cli]
----
systemctl status netapp-service-manager.service
----
. Supprimez les anciens points de terminaison de votre liste d’autorisation de pare-feu.




== Points de terminaison pour la NetApp Console et les agents de console pour la version 3.9.55 et les versions antérieures

Ces points de terminaison sont utilisés pour les agents de console 3.9.55 et versions antérieures.

[cols="2*"]
|===
| Points de terminaison | But 


 a| 
\ https://support.netapp.com \ https://mysupport.netapp.com
 a| 
Pour obtenir des informations de licence et envoyer des messages AutoSupport au support NetApp .



 a| 
\https://\*.api.bluexp.netapp.com \ https://api.bluexp.netapp.com \https://*.cloudmanager.cloud.netapp.com \ https://cloudmanager.cloud.netapp.com \ https://netapp-cloud-account.auth0.com \ https://netapp-cloud-account.us.auth0.com
| Pour fournir des fonctionnalités et des services au sein de la NetApp Console. 


 a| 
Choisissez entre deux ensembles de points de terminaison :

* Option 1 (recommandée)
+
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io

* Option 2
+
\https://*.blob.core.windows.net \ https://cloudmanagerinfraprod.azurecr.io


 a| 
Pour obtenir des images pour les mises à niveau de l'agent de console.

NetApp recommande d'autoriser les points de terminaison de l'option 1 dans votre pare-feu, car ils sont plus sécurisés, et d'interdire les points de terminaison de l'option 2, sauf si vous utilisez Ransomware Resilience ou Backup and Recovery.  Notez les points suivants à propos de ces points de terminaison :

* Les points de terminaison de l'option 1 sont pris en charge dans la version 3.9.47 et supérieure.  Les versions antérieures à la version 3.9.47 ne prennent pas en charge la compatibilité descendante.
* L'agent de console initie d'abord le contact avec les points de terminaison de l'option 2.  Si ces points de terminaison ne sont pas accessibles, il contacte automatiquement les points de terminaison de l'option 1.
* Si vous utilisez l’agent de console avec NetApp Backup and Recovery ou Ransomware Resilience, le système ne prend pas en charge les points de terminaison Option 1.  Autoriser les points de terminaison de l’option 2 et interdire l’option 1.


|===


== Points de terminaison du fournisseur de cloud contactés par l'agent de la console

Les agents de console doivent avoir accès à des points de terminaison supplémentaires s'ils sont déployés chez votre fournisseur de cloud.

Activez l’accès aux points de terminaison du fournisseur cloud avant d’installer l’agent de la console.

* link:task-install-agent-aws-console.html#networking-aws-agent["Configurer l'accès au réseau AWS pour un agent de console"]
* link:task-install-agent-azure-console.html#networking-azure-agent["Configurer l'accès au réseau Azure pour un agent de console"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["Configurer l'accès au réseau Google Cloud pour un agent de console"]


Les points de terminaison du fournisseur de cloud sont les mêmes pour toutes les versions.



== Points de terminaison des services de données contactés par l'agent de la console

L'agent de console nécessite un accès Internet sortant supplémentaire pour prendre en charge certains services de données NetApp et Cloud Volumes ONTAP.



=== Points de terminaison pour Cloud Volumes ONTAP

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["Points de terminaison pour Cloud Volumes ONTAP dans AWS"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Points de terminaison pour Cloud Volumes ONTAP dans Azure"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Points de terminaison pour Cloud Volumes ONTAP dans Google Cloud"]

