---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, Cloud Volumes ONTAP, days, running,  imdsv2, https tokens, Console agent 
summary: 'Les limitations connues identifient les plates-formes, les appareils ou les fonctions qui ne sont pas pris en charge par cette version du produit ou qui n"interagissent pas correctement avec elle. Examinez attentivement ces limitations.' 
---
= Limitations connues de la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plates-formes, les appareils ou les fonctions qui ne sont pas pris en charge par cette version du produit ou qui n'interagissent pas correctement avec elle. Examinez attentivement ces limitations.

Ces limitations sont spécifiques à la configuration de la NetApp Console et à l'administration : l'agent, la plateforme logicielle en tant que service (SaaS), et plus encore.



== Limitations de l'agent de console



=== Conflit possible avec les adresses IP dans la plage 172

La NetApp Console déploie un agent avec deux interfaces dont les adresses IP sont comprises dans les plages 172.17.0.0/16 et 172.18.0.0/16.

Si votre réseau dispose d’un sous-réseau configuré avec l’une de ces plages, vous risquez de rencontrer des échecs de connectivité depuis la console.  Par exemple, la découverte de clusters ONTAP sur site dans la console peut échouer.

Voir l'article de la base de connaissanceslink:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/Cloud_Manager_shows_inactive_as_Connector_IP_range_in_172.x.x.x_conflict_with_docker_network["Conflit IP de l'agent avec le réseau existant"] pour obtenir des instructions sur la façon de modifier l'adresse IP des interfaces de l'agent.



=== Le déchiffrement SSL est pris en charge uniquement pour Cloud Volumes ONTAP

Les serveurs proxy transparents sont pris en charge pour les agents associés à Cloud Volumes ONTAP uniquement. Vous ne pouvez pas utiliser de proxy transparent pour un agent s'il est utilisé avec d'autres NetApp data services. Si vous utilisez NetApp data services avec Cloud Volumes ONTAP, créez un agent dédié à Cloud Volumes ONTAP sur lequel vous pouvez utiliser un serveur proxy transparent.

Pour une sécurité renforcée, vous avez la possibilité delink:task-installing-https-cert.html["installer un certificat HTTPS signé par une autorité de certification (CA)"] .



=== Page blanche lors du chargement de l'interface utilisateur locale

Si vous chargez la console Web exécutée sur un agent, l'interface peut parfois ne pas s'afficher et vous obtenez simplement une page vierge.

Ce problème est lié à un problème de mise en cache.  La solution de contournement consiste à utiliser une session de navigateur Web privée ou en mode navigation privée.



=== Les hôtes Linux partagés ne sont pas pris en charge

L'agent n'est pas pris en charge sur une machine virtuelle partagée avec d'autres applications.  La VM doit être dédiée au logiciel agent.



=== Agents et extensions tiers

Les agents tiers ou les extensions de machine virtuelle ne sont pas pris en charge sur la machine virtuelle de l'agent.
