---
sidebar: sidebar 
permalink: reference-agent-maint-console-config-checker.html 
keywords: agent maintenance console, agent troubleshooting, network connectivity validation, agent validation, hardware requirements, deployment readiness, operational compliance, installation troubleshooting 
summary: 'Vous pouvez utiliser la console de maintenance de l"agent Console pour valider l"installation et la configuration d"un agent Console.' 
---
= Validation de l'agent de console avec la console de maintenance dans NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser la console de maintenance de l'agent Console pour valider l'installation et la configuration d'un agent Console.



== Accéder à la console de maintenance de l'agent

Vous pouvez accéder à la console de maintenance depuis l'hôte de l'agent de console. Accédez au répertoire suivant :

[source, cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----


== config-checker valider

Le `config-checker validate` Cette commande permet de valider la configuration d'un agent de console.



=== Paramètres

`--services <comma-separated list of services to validate>`--*REQUIS*--

[role="quick-margin-para"]
Choisissez un ou plusieurs services à valider. Les noms de services valides sont :

* `PLATFORM`qui valide la connectivité réseau aux points de terminaison requis de la Console ainsi que l'ouverture des ports requis pour l'agent de la Console.


`--validationTypes <comma-separated list of validation types to run>` --*OBLIGATOIRE*-- Choisissez un ou plusieurs types de validation à exécuter. Les types de validation valides sont :

* `NETWORK`qui valide la connectivité réseau aux points de terminaison Console requis.
* `HARDWARE`qui vérifie que l'hôte de l'agent répond aux exigences matérielles minimales pour l'agent Console.
+

NOTE: Lors de l'installation, NetApp vérifie que l'hôte de l'agent dispose d'au moins 80 % de l'espace disque total disponible, ce qui inclut 48 Go dans  `/opt` et 32 Go dans  `/var` (80 Go au total). Après l'installation, il est nécessaire qu'au moins 20 % de l'espace disque total reste disponible, ce qui inclut 12 Go dans  `/opt` et 8 Go dans  `/var` (20 Go au total).



`--proxy <url>`--*FACULTATIF*--

[role="quick-margin-para"]
Spécifie l'URL du serveur proxy à utiliser pour la validation.  Requis si votre agent est configuré pour utiliser un serveur proxy.

`--certs <paths>`--*FACULTATIF*--

[role="quick-margin-para"]
Spécifie le chemin d'accès à un ou plusieurs fichiers de certificat à utiliser pour la validation.  Les fichiers de certificat doivent être au format PEM.  Séparez les chemins multiples par des virgules.  Ce paramètre est requis si votre agent utilise un certificat personnalisé.



=== Exemples de validation du vérificateur de configuration

Les exemples suivants comprennent la validation de la connectivité réseau, des ports requis et des exigences matérielles, ainsi que différentes combinaisons d'utilisation d'un serveur proxy et de certificats personnalisés.

.Validation de la connectivité réseau et des exigences matérielles :
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE
----
.Validation lorsqu'un serveur proxy est utilisé pour l'agent :
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --proxy http://proxy.company.com:8080
----
.Validation lorsqu'un certificat est utilisé pour l'agent :
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --certs /path/to/cert1.pem,/path/to/cert2.pem
----


=== Afficher l'aide pour n'importe quelle commande

Pour afficher l'aide d'une commande, ajoutez `--help` à la commande.  Par exemple, pour afficher l'aide relative à la `proxy add` commande, utilisez la commande suivante :

[source, cli]
----
./agent-maint-console proxy add --help
----