---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, bluexp 
summary: 'La NetApp Console, l"agent de la NetApp Console et les services de données NetApp nécessitent un accès Internet sortant et la possibilité de contacter les points de terminaison nécessaires.' 
---
= Accès réseau pour la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La NetApp Console, l'agent de la NetApp Console et les services de données NetApp nécessitent un accès Internet sortant et la possibilité de contacter les points de terminaison nécessaires.

Vous devrez configurer l’accès au réseau pour les éléments suivants :

* Ordinateurs qui accèdent à la NetApp Console en tant que logiciel en tant que service (SaaS)
* Agents de console que vous installez sur site ou dans le cloud. Agents de console.



NOTE: Avec la version 4.0.0, NetApp a réduit les points de terminaison réseau requis pour la console et les agents de console, améliorant ainsi la sécurité et simplifiant le déploiement. Il est important de noter que tous les déploiements antérieurs à la version 4.0.0 continuent d’être entièrement pris en charge.  Bien que les points de terminaison précédents restent disponibles pour les agents existants, NetApp recommande fortement de mettre à jour les règles de pare-feu vers les points de terminaison actuels après avoir confirmé la réussite des mises à niveau des agents.link:reference-networking-saas-console-previous.html["Découvrez comment mettre à jour votre liste de points de terminaison."]



== Points de terminaison contactés par la NetApp Console et les agents de la console

Chaque agent que vous déployez et chaque ordinateur qui accède à la NetApp Console doivent disposer de connexions aux points de terminaison répertoriés ci-dessous.

Les agents de console déployés chez votre fournisseur de cloud doivent avoir accès aux points de terminaison respectifs de ce fournisseur de cloud.

[cols="2*"]
|===
| Points de terminaison | But 


| \ https://mysupport.netapp.com | Pour obtenir des informations sur les licences et envoyer des messages AutoSupport au support NetApp. 


| \ https://signin.b2c.netapp.com | Pour mettre à jour les informations d'identification du site de support NetApp (NSS) ou pour ajouter de nouvelles informations d'identification NSS à la NetApp Console. 


| \ https://support.netapp.com | Pour obtenir des informations sur les licences et envoyer des messages AutoSupport au support NetApp, ainsi que pour recevoir les mises à jour logicielles de Cloud Volumes ONTAP. 


| \https://api.bluexp.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://console.netapp.com \https://components.console.netapp.com \https://cdn.auth0.com | Pour fournir des fonctionnalités et des services au sein de la NetApp Console. 


 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
Pour obtenir des images pour les mises à niveau de l'agent de console.

|===


== Les points de terminaison du fournisseur de cloud ont contacté l'agent de la console

Les agents de console doivent avoir accès à des points de terminaison supplémentaires s'ils sont déployés chez votre fournisseur de cloud.

Configurez l’accès au point de terminaison du réseau du fournisseur de cloud avant d’installer l’agent de la console.

* link:task-install-agent-aws-console.html#networking-aws-agent["Configurer l'accès au réseau AWS pour un agent de console"]
* link:task-install-agent-azure-console.html#networking-azure-agent["Configurer l'accès au réseau Azure pour un agent de console"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["Configurer l'accès au réseau Google Cloud pour un agent de console"]




== Points de terminaison des services de données contactés par l'agent de la console

Certains services de données NetApp ainsi que Cloud Volumes ONTAP nécessitent que l'agent dispose d'un accès Internet sortant supplémentaire.



=== Points de terminaison pour Cloud Volumes ONTAP

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["Points de terminaison pour Cloud Volumes ONTAP dans AWS"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Points de terminaison pour Cloud Volumes ONTAP dans Azure"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Points de terminaison pour Cloud Volumes ONTAP dans Google Cloud"]




=== Points de terminaison pour les charges de travail

L'agent de la console doit pouvoir accéder au point de terminaison suivant pour les charges de travail NetApp .

[cols="2*"]
|===
| Points de terminaison | But 


 a| 
https://api.workloads.netapp.com
 a| 
La console Web contacte ce point de terminaison pour interagir avec les API Workload Factory afin de gérer et d'exploiter les charges de travail basées sur FSx pour ONTAP.

|===