---
sidebar: sidebar 
permalink: task-console-assistant.html 
keywords: bluexp,netapp console,console assistant,assistant,setup assistant,get started,quick start,first time user,first time setup,setup wizard 
summary: 'Si vous utilisez la NetApp Console pour la première fois, l"assistant de la console vous guide tout au long du processus de configuration initiale.  L"assistant vous aide à ajouter un compte NetApp Support Site (NSS), à ajouter un agent de console, à ajouter un cluster et à ajouter une licence ou un abonnement, ce qui facilite la prise en main de la gestion de vos données.' 
---
= Commencer à utiliser l'assistant de la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous êtes un nouvel utilisateur de la NetApp Console (SaaS) avec le rôle d'administrateur de l'organisation, vous pouvez utiliser l'assistant de la console pour vous guider tout au long du processus de configuration initiale. L'assistant vous aide à ajouter un compte NetApp Support Site (NSS), un agent Console, un cluster et une licence ou un abonnement, ce qui facilite la prise en main de la gestion de vos données.



[[required-roles-to-access-the-console-assistant]]
== Rôles requis pour accéder à l'assistant de la console

L'assistant de console est uniquement disponible pour les utilisateurs disposant du rôle d'administrateur d'organisation.

Par défaut, la NetApp Console affiche l'assistant de console sur la page d'accueil pour les nouveaux utilisateurs qui possèdent le rôle d'administrateur de l'organisation. Elle reste disponible jusqu'à ce que vous ayez terminé les tâches obligatoires de création d'un agent Console et d'ajout d'un système.

Utilisez l'assistant pour effectuer ces tâches, qui constituent la configuration minimale requise pour votre NetApp Console :

* Ajoutez un compte de site de support NetApp (NSS).
+
link:task-adding-nss-accounts.html["Apprenez comment ajouter un compte NSS"].

* Connectez-vous à votre infrastructure de stockage en déployant un agent Console.
+
link:task-install-agent-on-prem.html["Découvrez comment installer un agent Console sur site."]

* Gérez un système de stockage en ajoutant ou en découvrant un cluster
* Ajoutez un abonnement au marketplace ou une licence PAYGO.
+
link:https://docs.netapp.com/us-en/console-licenses-subscriptions/index.html["Apprenez comment ajouter des licences et des abonnements"^].

* Consultez les informations sur les services de données.

