---
sidebar: sidebar 
permalink: task-upgrade-agent.html 
keywords: upgrade, manual upgrade, agent upgrade, manual agent upgrade, upgrade agent manually, private mode upgrade, offline upgrade, upgrade private mode, connector upgrade, agent upgrade 
summary: 'L"agent Console est automatiquement mis à jour lorsqu"il dispose d"une connectivité sortante. Si votre agent Console ne dispose pas de connectivité sortante, vous pouvez le mettre à niveau manuellement (par exemple avec le mode privé).' 
---
= Gérer les mises à niveau de l'agent de la console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'agent Console est automatiquement mis à jour lorsqu'il dispose d'une connectivité sortante. Si votre agent Console ne dispose pas de connectivité sortante, vous pouvez le mettre à niveau manuellement (par exemple avec le mode privé).



== Mettre à niveau l'agent de la console

L'agent de la console doit redémarrer pendant le processus de mise à niveau afin que la NetApp Console ne soit pas disponible pendant la mise à niveau.

.Étapes
. Téléchargez le logiciel de l'agent de la console à partir du https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Site de support NetApp"^] .
. Copiez le programme d’installation sur l’hôte Linux.
. Attribuer des autorisations pour exécuter le script.
+
[source, cli]
----
chmod +x /path/NetApp-Console-Agent-Offline-<version>
----
+
Où <version> est la version de l’agent de console que vous avez téléchargé.

. Exécutez le script d’installation :
+
[source, cli]
----
sudo /path/NetApp-Console-Agent-Offline-<version>
----
+
Où <version> est la version de l'agent que vous avez téléchargé.

. Une fois la mise à niveau terminée, vous pouvez vérifier la version de l'agent en accédant à *Administration > Support > Agents*.

