---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: Après vous être inscrit à la NetApp Console, vous pouvez vous connecter à partir de la console Web pour commencer à gérer vos données et votre infrastructure de stockage. 
---
= Connectez-vous à la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Après vous être inscrit à la NetApp Console, vous pouvez vous connecter à partir de la console Web pour commencer à gérer vos données et votre infrastructure de stockage.

Après votre inscription, l'administrateur de votre organisation Console doit ajouter votre compte utilisateur à une organisation avant que vous puissiez accéder à des ressources. Si vous vous connectez mais ne voyez aucune ressource, contactez l'administrateur de votre organisation. link:task-user-settings.html#contact-admin["Contactez l'administrateur de votre organisation"].

.Étapes
. Accédez à l’URL de la NetApp Console. L’URL dépend du mode de Console que votre organisation utilise :
+
** *Mode standard* : Ouvrez un navigateur Web et accédez à  https://console.netapp.com["NetApp Console"^].
** **Mode restreint ou mode privé** : Ouvrez un navigateur Web et accédez à l'adresse IP où l'agent Console est installé.


. Sur la page *Connexion*, saisissez l'adresse e-mail associée à votre connexion.
. Selon la méthode d'authentification associée à votre connexion, vous serez invité à saisir vos identifiants.
+
** Vos informations d'identification du site de support NetApp (NSS) existantes
** Un compte NetApp Console utilisant votre adresse e-mail et un mot de passe
** Une connexion fédérée si votre administrateur a configuré la fédération d'identité pour votre organisation



