---
sidebar: sidebar 
permalink: task-iam-manage-members-permissions.html 
keywords: user, service account, member, role, permissions, organization, project, folder, iam, identity and access management, federated groups, SSO, access roles, add members, grant permissions 
summary: Gérez les membres de votre organisation pour fournir des autorisations à différents niveaux de la hiérarchie des ressources de votre organisation. 
---
= Ajouter des utilisateurs à une organisation NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dans la console, vous accordez aux utilisateurs l'accès aux projets ou aux dossiers en fonction d'un rôle d'accès. Un rôle d'accès comprend un ensemble d'autorisations permettant à un membre (utilisateur ou compte de service) d'effectuer des actions spécifiques au niveau correspondant de la hiérarchie des ressources.

.Rôles d'accès requis
Super administrateur, administrateur d'organisation ou administrateur de dossier ou de projet (pour les dossiers et les projets qu'ils administrent). link:reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès"].



[[understand-how-access-is-granted-in-netapp-console]]
== Comprendre comment l'accès est accordé dans la NetApp Console

La NetApp Console utilise le contrôle d'accès basé sur les rôles (RBAC) pour gérer les autorisations. Attribuez des rôles aux utilisateurs individuellement ou via des groupes fédérés. Chaque rôle définit les actions autorisées pour des ressources spécifiques.

Veuillez noter les points suivants concernant l'octroi d'accès dans la NetApp Console:

* Tous les utilisateurs doivent d'abord s'inscrire à la NetApp Console avant de pouvoir accéder aux ressources, même s'ils font partie d'un groupe fédéré.
* Vous devez attribuer explicitement un rôle à chaque utilisateur dans la console avant qu'il puisse accéder aux ressources, même s'il est membre d'un groupe fédéré auquel un rôle a été attribué.
* Vous pouvez ajouter des comptes de service directement depuis la console et leur attribuer des rôles.
* Vous pouvez choisir parmi les rôles pris en charge lors de l'attribution de rôles aux utilisateurs ou aux comptes de service.




[[add-members-to-your-organization]]
[[add-members]]
== Ajoutez des membres à votre organisation

La NetApp Console prend en charge trois types de membres : les comptes d’utilisateurs, les comptes de service et les groupes fédérés.

Les utilisateurs doivent s'inscrire à la NetApp Console avant que vous puissiez les ajouter et leur attribuer un rôle, même s'ils font partie d'un groupe fédéré. Créez des comptes de service directement dans la console.

Pour accéder aux ressources, tous les membres doivent se voir attribuer au moins un rôle explicite.

Lors de l'ajout d'un membre, choisissez le niveau de ressource (organisation, dossier ou projet) et attribuez-lui un ou plusieurs rôles avec les autorisations nécessaires.



[[add-a-user]]
=== Ajouter un utilisateur

Les utilisateurs s'inscrivent à la NetApp Console, mais un administrateur d'organisation, de dossier ou de projet doit les ajouter à une organisation, un dossier ou un projet pour qu'ils puissent accéder aux ressources.

.Avant de commencer :
L'utilisateur doit déjà s'être inscrit à la NetApp Console. S'ils ne se sont pas encore inscrits, dirigez-les vers link:task-sign-up-saas.html["Inscrivez-vous à la NetApp Console."]


NOTE: Si vous ajoutez un utilisateur membre d'un groupe fédéré, assurez-vous que l'utilisateur s'est déjà inscrit à la NetApp Console et qu'un rôle lui a été explicitement attribué dans la Console. NetApp recommande d'attribuer un rôle d'accès minimal, tel que Organization viewer.

.Étapes
. Sélectionnez *Administration > Identité et accès*.
. Sélectionnez *Membres*.
. Sélectionnez *Ajouter un membre*.
. Pour *Type de membre*, gardez *Utilisateur* sélectionné.
. Pour *E-mail de l'utilisateur*, saisissez l'adresse e-mail de l'utilisateur associée à la connexion qu'il a créée.
. Utilisez la section *Sélectionnez une organisation, un dossier ou un projet* pour choisir le niveau de votre hiérarchie de ressources pour lequel le membre doit disposer d'autorisations.
+
Notez ce qui suit :

+
** Vous pouvez sélectionner uniquement les dossiers et les projets pour lesquels vous disposez des autorisations.
** Lorsque vous sélectionnez une organisation ou un dossier, vous accordez au membre l'autorisation d'accéder à tout son contenu.
** Vous ne pouvez attribuer le rôle *Administrateur de l'organisation* qu'au niveau de l'organisation.


. *Sélectionnez une catégorie* puis sélectionnez un *Rôle* qui fournit au membre des autorisations pour les ressources associées à l'organisation, au dossier ou au projet que vous avez sélectionné.
+
Seuls les rôles pris en charge sont affichés dans la liste déroulante. link:reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès"].

. Pour donner accès à davantage de dossiers, de projets ou de rôles, sélectionnez *Ajouter un rôle*, choisissez le dossier, le projet ou la catégorie de rôle, puis sélectionnez un rôle.
. Sélectionnez *Ajouter*.
+
La console envoie des instructions par courriel à l'utilisateur.





[[add-a-service-account]]
[[service-account]]
=== Ajouter un compte de service

Les comptes de service vous permettent d'automatiser les tâches et de vous connecter en toute sécurité aux API de la console. Choisissez un ID client et un secret pour les configurations simples, ou un JWT (JSON Web Token) pour une sécurité renforcée dans les environnements automatisés ou natifs du cloud. Choisissez la méthode qui répond à vos exigences de sécurité.

.Avant de commencer :
Pour l'authentification JWT, préparez votre clé publique ou votre certificat.

.Étapes
. Sélectionnez *Administration > Identité et accès*.
. Sélectionnez *Membres*.
. Sélectionnez *Ajouter un membre*.
. Pour *Type de membre*, sélectionnez *Compte de service*.
. Saisissez un nom pour le compte de service.
. Pour utiliser l'authentification JWT, sélectionnez *Utiliser l'authentification JWT par clé privée* et téléchargez votre clé ou certificat RSA public. Ignorez cette étape si vous utilisez un ID client et un secret.
+
Téléversez votre certificat X.509 au format PEM, CRT ou CER.

+
.. Configurez les notifications d'expiration de votre certificat.  Choisissez entre sept jours ou 30 jours.  Les notifications d'expiration sont envoyées par e-mail et affichées dans la console aux utilisateurs ayant le rôle de super administrateur ou d'administrateur d'organisation.


. Utilisez la section *Sélectionnez une organisation, un dossier ou un projet* pour choisir le niveau de votre hiérarchie de ressources pour lequel le membre doit disposer d'autorisations.
+
Notez ce qui suit :

+
** Vous ne pouvez sélectionner que les dossiers et les projets pour lesquels vous disposez d'autorisations.
** La sélection d’une organisation ou d’un dossier accorde au membre des autorisations sur tout son contenu.
** Vous ne pouvez attribuer le rôle *Administrateur de l'organisation* qu'au niveau de l'organisation.


. Sélectionnez une *Catégorie*, puis un *Rôle* qui confère au membre les autorisations nécessaires pour accéder aux ressources de l'organisation, du dossier ou du projet que vous avez sélectionné.
+
link:reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès"] .

. Pour donner accès à davantage de dossiers, de projets ou de rôles, sélectionnez *Ajouter un rôle*, choisissez le dossier, le projet ou la catégorie de rôle, puis sélectionnez un rôle.
. Si vous n'avez pas utilisé l'authentification JWT, téléchargez ou copiez l'identifiant client et le secret client.
+
La console n'affiche le secret client qu'une seule fois. Copiez-le en lieu sûr ; vous pourrez le recréer plus tard si vous le perdez.

. Si vous avez choisi l'authentification JWT, téléchargez ou copiez l'ID client et l'audience JWT. La console n'affiche ces informations qu'une seule fois et ne permet pas de les récupérer ultérieurement.
. Sélectionnez *Fermer*.




[[add-a-federated-group-to-your-organization]]
== Ajoutez un groupe fédéré à votre organisation

Vous pouvez ajouter un groupe fédéré de votre fournisseur d'identité (IdP) à votre organisation et lui attribuer un ou plusieurs rôles. Les membres du groupe fédéré héritent des rôles que vous attribuez au groupe dans la console.


IMPORTANT: Lorsque vous ajoutez un groupe fédéré à la Console et lui attribuez un rôle, seuls les utilisateurs qui sont membres du groupe dans votre IdP et qui se sont déjà inscrits à la NetApp Console et se sont vu explicitement attribuer un rôle dans la Console peuvent accéder aux ressources. NetApp recommande d'attribuer à ces utilisateurs un rôle d'accès minimal, tel que Lecteur de l'organisation.

Avant d'attribuer un rôle à un groupe fédéré, assurez-vous des points suivants :

* Configurez la fédération entre votre fournisseur d'identité et la console. link:concept-federation.html["Apprenez à configurer une fédération."]
* Le groupe doit déjà exister dans votre fournisseur d'identité et avoir été affecté à l'accès à l'application Console.


.Étapes
. Sélectionnez *Administration > Identité et accès*.
. Sélectionnez *Membres*.
. Sélectionnez *Ajouter un membre*.
. Pour *Type de membre*, sélectionnez *Groupe fédéré*.
. Sélectionnez la fédération dont le groupe est membre.
. Pour *Nom du groupe*, veuillez saisir le nom exact du groupe dans votre fournisseur d'identité.
. Utilisez la section *Sélectionnez une organisation, un dossier ou un projet* pour choisir le niveau de votre hiérarchie de ressources pour lequel le membre doit disposer d'autorisations.
+
Notez ce qui suit :

+
** Vous ne pouvez sélectionner que les dossiers et les projets pour lesquels vous disposez d'autorisations.
** La sélection d’une organisation ou d’un dossier accorde au membre des autorisations sur tout son contenu.
** Vous ne pouvez attribuer le rôle *Administrateur de l'organisation* qu'au niveau de l'organisation.


. Sélectionnez une *Catégorie*, puis un *Rôle* qui confère au membre les autorisations nécessaires pour accéder aux ressources de l'organisation, du dossier ou du projet que vous avez sélectionné.
+
Seuls les rôles pris en charge sont affichés dans la liste déroulante. link:reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès"].

. Pour donner accès à davantage de dossiers, de projets ou de rôles, sélectionnez *Ajouter un rôle*, choisissez le dossier, le projet ou la catégorie de rôle, puis sélectionnez un rôle.




[[related-information]]
== Informations connexes

* link:concept-identity-and-access-management.html["En savoir plus sur la gestion des identités et des accès dans la NetApp Console"]
* link:task-iam-get-started.html["Démarrer avec l'identité et l'accès"]
* link:reference-iam-predefined-roles.html["Rôles d'accès à la NetApp Console"]
* https://docs.netapp.com/us-en/console-automation/tenancyv4/overview.html["En savoir plus sur l'API pour l'identité et l'accès"^]

