---
sidebar: sidebar 
permalink: task-uninstall-agent.html 
keywords: uninstall, remove connector, uninstall connector, uninstall agent, remove agent 
summary: 'Désinstallez un agent de Console pour résoudre les problèmes ou le supprimer définitivement de l"hôte. La procédure à suivre dépend du mode de déploiement que vous utilisez. Une fois que vous avez supprimé un agent de Console de votre environnement, vous pouvez le supprimer de la Console.' 
---
= Désinstaller et supprimer un agent de console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Désinstallez un agent de Console pour résoudre les problèmes ou le supprimer définitivement de l'hôte. La procédure à suivre dépend du mode de déploiement que vous utilisez. Une fois que vous avez supprimé un agent de Console de votre environnement, vous pouvez le supprimer de la Console.



[[uninstall-the-agent-when-it-has-outbound-connectivity]]
== Désinstallez l'agent lorsqu'il dispose d'une connectivité sortante

Si vous utilisez le mode standard ou le mode restreint (en d'autres termes, l'hôte de l'agent dispose d'une connectivité sortante), vous devez suivre les étapes ci-dessous pour désinstaller l'agent.

.Étapes
. Connectez-vous à la machine virtuelle Linux pour l’agent.
. Depuis l’hôte Linux, exécutez le script de désinstallation :
+
`/opt/application/netapp/service-manager-2/uninstall.sh [silent]`

+
_silent_ exécute le script sans vous demander de confirmation.





[[uninstall-the-agent-when-it-has-no-outbound-connectivity]]
== Désinstallez l'agent lorsqu'il n'a aucune connectivité sortante

Si votre agent ne dispose d'aucune connectivité sortante (par exemple, en mode privé), vous devez supprimer manuellement le logiciel agent de l'hôte.

.Étape
. Connectez-vous à la machine virtuelle Linux pour l’agent de console.
. Depuis l'hôte Linux, exécutez les commandes suivantes :
+
[source, cli]
----
/opt/application/netapp/ds/cleanup.sh
rm -rf /opt/application/netapp/
----
. Depuis l'hôte Linux, supprimez les anciens fichiers image de conteneur inutilisés pour libérer de l'espace dans le répertoire /var pour la réinstallation.
+
[role="tabbed-block"]
====
.Podman
--
[source, cli]
----
podman system prune --all
----
--
.Docker
--
[source, cli]
----
docker system prune -a
----
--
====




[[remove-console-agents-from-the-console]]
== Supprimer les agents de la console

Si vous avez supprimé une machine virtuelle d'agent ou désinstallé l'agent, vous devez la retirer de la liste des agents dans la console. Après la suppression d'une machine virtuelle d'agent ou la désinstallation du logiciel d'agent, l'agent affiche l'état *Déconnecté* dans la console.

Notez les points suivants concernant la suppression d’un agent de console :

* Cette action ne supprime pas la machine virtuelle.
* Cette action ne peut pas être annulée : une fois que vous avez supprimé un agent de console, vous ne pouvez pas le rajouter.


.Étapes
. Sélectionnez *Administration > Agents*.
. Sur la page *Aperçu*, sélectionnez le menu d'actions d'un agent déconnecté et sélectionnez *Supprimer l'agent*.
. Saisissez le nom de l'agent pour confirmer, puis sélectionnez *Supprimer*.

