---
sidebar: sidebar 
permalink: task-maintain-agents.html 
keywords: agent operating system, agent maintenance, vm maintenance, os updates, operating system updates, stop agent, restart agent, notifications, agent health, agent disk space, agent cpu usage, agent ram usage, agent vm, connector, connector health 
summary: La maintenance du système d’exploitation sur l’hôte de l’agent est de votre responsabilité.  Par exemple, vous devez appliquer les mises à jour de sécurité au système d’exploitation sur l’hôte de l’agent de console en suivant les procédures standard de votre entreprise pour la distribution du système d’exploitation. 
---
= Maintenir la machine virtuelle pour un agent Console installé manuellement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lors de l'installation manuelle d'un agent Console, la maintenance du système d'exploitation sur l'hôte de l'agent relève de votre responsabilité (celle du client). Par exemple, vous (le client) devez appliquer les mises à jour de sécurité au système d'exploitation de l'hôte de l'agent en suivant les procédures standard de votre entreprise en matière de distribution de systèmes d'exploitation.



== Appliquer les mises à jour du système d'exploitation à l'hôte de l'agent

Appliquez les correctifs de sécurité du système d’exploitation sans arrêter les services hôtes de l’agent.

Pour garantir la compatibilité avec les configurations prises en charge, vous devez empêcher la mise à niveau de Docker ou de Podman lors des mises à jour système de routine. Vous pouvez le faire soit en excluant temporairement Docker ou Podman lors des mises à jour, soit en configurant de manière permanente le gestionnaire de paquets pour ignorer les mises à jour de Docker ou de Podman.

Voici des exemples de procédure pour exclure les mises à jour de Docker ou Podman sur différentes distributions Linux. Consultez la documentation de votre distribution Linux pour obtenir les instructions les plus récentes sur la manière d'exclure des paquets des mises à jour.

.Exemple Podman
[source, bash]
----
sudo yum update --exclude=podman
sudo yum upgrade
----
.Exemple Docker
[source, bash]
----
sudo apt-mark hold docker-ce docker-ce-cli containerd.io
sudo apt update
sudo apt upgrade
----


== Type de machine virtuelle ou d'instance

Si vous créez un agent de console à partir de la console, il déploie une instance de machine virtuelle dans votre fournisseur de cloud avec une configuration par défaut.  Après avoir créé l'agent, ne passez pas à une instance de machine virtuelle plus petite avec moins de CPU ou de RAM.

Le tableau suivant répertorie les exigences en matière de CPU et de RAM :

processeur:: 8 cœurs ou 8 vCPU
BÉLIER:: 32 Go


link:reference-agent-default-config.html["En savoir plus sur la configuration par défaut de l'agent"] .



== Surveiller l'agent

La console vous avertit lorsque la machine virtuelle de l'agent n'est pas saine, notamment en cas de problèmes d'espace disque, de RAM et de processeur.  Surveillez ces notifications dans le centre de notifications de la console ou configurez des notifications par e-mail.  Des augmentations occasionnelles de l'espace disque, de la mémoire ou de l'utilisation du processeur sont normales, mais si cela se produit fréquemment, vous devez prendre des mesures pour résoudre le problème.

Par exemple, la console vous avertit lorsqu'une ressource d'agent (CPU, RAM ou espace disque) dépasse 90 % de sa capacité totale pendant 30 minutes consécutives.  Par la suite, si l’utilisation des ressources descend en dessous de ce seuil, la notification s’affiche comme résolue (verte) dans le Centre de notifications.


NOTE: Travaillez avec le support NetApp si vous avez des questions sur la modification de votre machine virtuelle agent.

link:https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#notification-center["Apprendre encore plus."^]

[cols="47,47"]
|===
| Notification | Action nécessaire 


| L'espace disque est trop élevé | link:https://kb.netapp.com/Cloud/BlueXP/Cloud_Manager/How_to_resolve_disk_space_issues_on_BlueXP_connector_VM["Consultez l'article de la base de connaissances NetApp"^] . 


| L'utilisation du processeur est trop élevée | Augmentez la taille du processeur de la machine virtuelle de l’agent dans votre fournisseur de cloud ou sur site, selon l’endroit où vous l’avez installé.  Vous pouvez également créer des agents supplémentaires et répartir la charge de travail sur plusieurs agents.  L'utilisation de la RAM peut varier en fonction de votre environnement, des charges de travail ONTAP , du nombre de systèmes Cloud Volumes ONTAP et des services de données que vous utilisez. 


| L'utilisation de la RAM est trop élevée | Augmentez la RAM de la machine virtuelle de l’agent dans votre fournisseur de cloud ou sur site, selon l’endroit où vous l’avez installé.  Vous pouvez également créer des agents supplémentaires et répartir la charge de travail sur plusieurs agents.  L'utilisation de la RAM peut varier en fonction de votre environnement, des charges de travail ONTAP , du nombre de systèmes Cloud Volumes ONTAP et des services de données que vous utilisez. 
|===


== Arrêt et démarrage de la machine virtuelle de l'agent

Si nécessaire, arrêtez et démarrez la machine virtuelle de l'agent à l'aide de la console de votre fournisseur de cloud ou des procédures standard sur site.

link:concept-agents.html#agents-must-be-operational-at-all-times["Sachez que l'agent de la console doit être opérationnel à tout moment"] .



== Se connecter à la machine virtuelle Linux

Si vous devez vous connecter à la machine virtuelle Linux sur laquelle l’agent s’exécute, utilisez les options de connectivité de votre fournisseur de cloud.

AWS:: Lorsque vous créez l'instance d'agent dans AWS, fournissez une clé d'accès AWS et une clé secrète.  Vous pouvez utiliser cette paire de clés pour vous connecter en SSH à l'instance.  Utilisez le nom d'utilisateur « ubuntu » pour l'instance Linux EC2.  Pour les agents créés avant mai 2023, utilisez le nom d'utilisateur « ec2-user ».
+
--
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html["Documentation AWS : connectez-vous à votre instance Linux"^]

--
Azuré:: Lorsque vous créez la machine virtuelle de l’agent dans Azure, vous spécifiez un nom d’utilisateur et choisissez de vous authentifier avec un mot de passe ou une clé publique SSH.  Utilisez la méthode d’authentification que vous avez choisie pour vous connecter à la machine virtuelle.
+
--
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm["Azure Docs : Connectez-vous à votre machine virtuelle via SSH"^]

--
Google Cloud:: Vous ne pouvez pas spécifier de méthode d'authentification lorsque vous créez un agent dans Google Cloud.  Cependant, vous pouvez vous connecter à l'instance de machine virtuelle Linux à l'aide de la console Google Cloud ou de Google Cloud CLI (gcloud).
+
--
https://cloud.google.com/compute/docs/instances/connecting-to-instance["Google Cloud Docs : Se connecter aux machines virtuelles Linux"^]

--

