---
sidebar: sidebar 
permalink: task-organization-verify.html 
keywords: adding, creating, netapp support site account, nss, update account, update nss account, update nss credentials, delete nss account, remove nss account, change working environment, working environment nss, digital wallet, license, change system, system nss, licenses and subscriptions 
summary: Associez un compte de site de support NetApp à votre organisation NetApp Console pour activer les flux de travail clés pour Cloud Volumes ONTAP.  Ces informations d’identification NSS sont associées à l’ensemble de l’organisation. 
---
= Vérifiez votre organisation NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous utilisez Digital Advisor, vous devez vérifier votre organisation Console si votre entreprise possède plusieurs comptes professionnels auprès de NetApp. Digital Advisor peut afficher plusieurs comptes NetApp qui ne sont pas liés à votre organisation Console. Pour vous assurer de n'afficher que les ressources associées à votre organisation Console, vous pouvez vérifier l'identifiant de l'entreprise que vous souhaitez associer à votre organisation Console.

La console prend également en charge l’association d’un compte NSS par compte utilisateur. link:task-manage-user-credentials.html["Apprenez à gérer les informations d'identification au niveau utilisateur"] .



== Avant de commencer

Vous devez disposer du rôle d'administrateur de l'organisation pour vérifier votre organisation et votre utilisateur doit également être associé à un compte NetApp Support Site (NSS). link:task-adding-nss-accounts["Apprenez comment associer votre compte NSS"].


NOTE: Si votre entreprise ne possède qu'un seul compte professionnel et que votre utilisateur est associé à un compte NetApp Support Site, votre organisation est vérifiée automatiquement.



== Vérifiez votre organisation

.Étapes
. Si votre utilisateur a accès à plusieurs organisations, sélectionnez l'organisation que vous souhaitez vérifier dans le menu déroulant Organization.
. Dans *Administration > Identité et accès*.
. Sélectionnez *Organisation*.

