---
sidebar: sidebar 
permalink: task-federation-adfs.html 
keywords: federation, active directory federation services, adfs, ad fs, single sign-on, microsoft, federate, federated connection, SSO, identity federation, identity management, corporate identity 
summary: 'Fédérez-vous avec vos services de fédération Active Directory (AD FS) pour activer l"authentification unique (SSO) pour la NetApp Console.  Cela permet aux utilisateurs de se connecter en utilisant leurs identifiants d’entreprise.' 
---
= Fédérer la NetApp Console avec les services de fédération Active Directory (AD FS)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Fédérez vos services de fédération Active Directory (AD FS) avec la NetApp Console pour activer l'authentification unique (SSO) pour la NetApp Console.  Cela permet aux utilisateurs de se connecter à la console en utilisant leurs identifiants d’entreprise.

.Rôles requis
Le rôle d'administrateur de fédération est requis pour créer et gérer des fédérations.  Le spectateur de la Fédération peut voir la page de la Fédération.link:reference-iam-predefined-roles.html["En savoir plus sur les rôles d’accès."]


NOTE: Vous pouvez vous fédérer avec votre IdP d'entreprise ou avec le site de support NetApp .  NetApp recommande de choisir l’un ou l’autre, mais pas les deux.

NetApp prend uniquement en charge l'authentification unique initiée par le fournisseur de services (SP).  Tout d’abord, configurez le fournisseur d’identité pour qu’il approuve la NetApp Console en tant que fournisseur de services.  Ensuite, créez une connexion dans la console en utilisant la configuration de votre fournisseur d’identité.

Vous pouvez configurer la fédération avec votre serveur AD FS pour activer l'authentification unique (SSO) pour la NetApp Console.  Le processus implique la configuration de votre AD FS pour approuver la console en tant que fournisseur de services, puis la création de la connexion dans la NetApp Console.

.Avant de commencer
* Un compte IdP avec des privilèges administratifs est requis.  Coordonnez-vous avec votre administrateur IdP pour terminer les étapes.
* Identifiez le domaine que vous souhaitez utiliser pour la fédération.  Vous pouvez utiliser votre domaine de messagerie ou un autre domaine que vous possédez.  Si vous souhaitez utiliser un domaine autre que votre domaine de messagerie, vous devez d’abord vérifier le domaine dans la console.  Vous pouvez le faire en suivant les étapes décrites dans lelink:task-federation-verify-domain.html["Vérifiez votre domaine dans la NetApp Console"] sujet.


.Étapes
. Sélectionnez *Administration > Identité et accès*.
. Sélectionnez *Fédération* pour afficher la page *Fédérations*.
. Sélectionnez *Configurer une nouvelle fédération*.
. Entrez les détails de votre domaine :
+
.. Choisissez si vous souhaitez utiliser un domaine vérifié ou votre domaine de messagerie.  Le domaine de messagerie est le domaine associé au compte avec lequel vous êtes connecté.
.. Entrez le nom de la fédération que vous configurez.
.. Si vous choisissez un domaine vérifié, sélectionnez le domaine dans la liste.


. Sélectionnez *Suivant*.
. Pour votre méthode de connexion, choisissez *Protocole* puis sélectionnez *Active Directory Federation Services (AD FS)*.
. Sélectionnez *Suivant*.
. Créez une approbation de partie de confiance sur votre serveur AD FS.  Vous pouvez utiliser PowerShell ou le configurer manuellement sur votre serveur AD FS.  Consultez la documentation AD FS pour plus de détails sur la création d’une approbation de partie de confiance.
+
.. Créez la confiance à l’aide de PowerShell en utilisant le script suivant :
+
[source, powershell]
----
(new-object Net.WebClient -property @{Encoding = [Text.Encoding]::UTF8}).DownloadString("https://raw.github.com/auth0/AD FS-auth0/master/AD FS.ps1") | iex
AddRelyingParty "urn:auth0:netapp-cloud-account" "https://netapp-cloud-account.auth0.com/login/callback"
----
.. Vous pouvez également créer l’approbation manuellement dans la console de gestion AD FS.  Utilisez les valeurs suivantes de la NetApp Console lors de la création de l’approbation :
+
*** Lors de la création de l'identifiant de confiance de confiance, utilisez la valeur **YOUR_TENANT** : `netapp-cloud-account`
*** Lorsque vous sélectionnez *Activer la prise en charge de WS-Federation*, utilisez la valeur **YOUR_AUTH0_DOMAIN** : `netapp-cloud-account.auth0.com`


.. Après avoir créé l’approbation, copiez l’URL des métadonnées à partir de votre serveur AD FS ou téléchargez le fichier de métadonnées de fédération.  Vous aurez besoin de cette URL ou de ce fichier pour terminer la connexion dans la console.


+
NetApp recommande d’utiliser l’URL des métadonnées pour permettre à la NetApp Console de récupérer automatiquement la dernière configuration AD FS.  Si vous téléchargez le fichier de métadonnées de fédération, vous devrez le mettre à jour manuellement dans la NetApp Console chaque fois que des modifications sont apportées à votre configuration AD FS.

. Revenez à la console et sélectionnez *Suivant* pour créer la connexion.
. Créez la connexion avec AD FS.
+
.. Saisissez l'*URL AD FS* que vous avez copiée à partir de votre serveur AD FS à l'étape précédente ou téléchargez le fichier de métadonnées de fédération que vous avez téléchargé à partir de votre serveur AD FS.


. Sélectionnez *Créer une connexion*.  La création de la connexion peut prendre quelques secondes.
. Sélectionnez *Suivant*.
. Sélectionnez *Tester la connexion* pour tester votre connexion.  Vous êtes dirigé vers une page de connexion pour votre serveur IdP.  Connectez-vous avec vos identifiants IdP pour terminer le test et revenez à la console pour activer la connexion.
. Sélectionnez *Suivant*.
. Sur la page *Activer la fédération*, vérifiez les détails de la fédération, puis sélectionnez *Activer la fédération*.
. Sélectionnez *Terminer* pour terminer le processus.


Une fois la fédération activée, les utilisateurs peuvent se connecter à la NetApp Console à l’aide de leurs informations d’identification d’entreprise.
