---
sidebar: sidebar 
permalink: task-manage-user-credentials.html 
keywords: credentials, ontap credentials, update ontap credentials, update ontap password, nss account, nss credentials, nss login, nss password 
summary: 'Selon les actions que vous avez effectuées dans la console, vous avez peut-être associé les informations d"identification ONTAP et les informations d"identification du site de support NetApp (NSS) à votre connexion utilisateur.  Vous pouvez afficher et gérer ces informations d"identification après les avoir associées.  Par exemple, si vous modifiez le mot de passe de ces informations d’identification, vous devrez mettre à jour le mot de passe dans la console.' 
---
= Gérer les informations d'identification associées à votre connexion à la console NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Selon les actions que vous avez effectuées dans la console, vous avez peut-être associé les informations d'identification ONTAP et les informations d'identification du site de support NetApp (NSS) à votre connexion utilisateur.  Vous pouvez afficher et gérer ces informations d'identification après les avoir associées.  Par exemple, si vous modifiez le mot de passe de ces informations d’identification, vous devrez mettre à jour le mot de passe dans la console.



== Informations d'identification ONTAP

Les utilisateurs ont besoin des informations d’identification d’administrateur ONTAP pour découvrir les clusters ONTAP dans la console.  Cependant, l'accès à ONTAP System Manager dépend de l'utilisation ou non d'un agent de console.

.Sans agent de console
Les utilisateurs sont invités à saisir leurs informations d’identification ONTAP pour accéder à ONTAP System Manager pour le cluster.  Les utilisateurs peuvent choisir d'enregistrer ces informations d'identification dans la console, ce qui signifie qu'ils ne seront pas invités à les saisir à chaque fois.  Les informations d'identification de l'utilisateur ne sont visibles que par l'utilisateur concerné et peuvent être gérées à partir de la page Informations d'identification de l'utilisateur.

.Avec un agent de console
Par défaut, les utilisateurs ne sont pas invités à saisir leurs informations d’identification ONTAP pour accéder à ONTAP System Manager.  Cependant, un administrateur de console (avec le rôle d’administrateur d’organisation) peut configurer la console pour inviter les utilisateurs à saisir leurs informations d’identification ONTAP .  Lorsque ce paramètre est activé, les utilisateurs doivent saisir leurs informations d'identification ONTAP à chaque fois.

link:task-ontap-access-agent.html["Apprendre encore plus."^]



== Informations d'identification NSS

Les informations d'identification NSS associées à votre connexion à la console NetApp permettent l'enregistrement du support, la gestion des cas et l'accès à Digital Advisor.

* Lorsque vous accédez à *Support > Ressources* et que vous vous inscrivez à l'assistance, vous êtes invité à associer les informations d'identification NSS à votre connexion.
+
Cela enregistre votre organisation ou votre compte pour l'assistance et active le droit à l'assistance.  Un seul utilisateur de votre organisation doit associer un compte de site de support NetApp à sa connexion pour s'inscrire au support et activer le droit au support.  Une fois cette opération terminée, la page *Ressources* indique que votre compte est enregistré pour l'assistance.

+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-support-registration.html["Apprenez comment vous inscrire pour bénéficier de l'assistance"^]

* Lorsque vous accédez à *Administration > Support > Gestion des cas*, vous êtes invité à saisir vos informations d'identification NSS, si vous ne l'avez pas déjà fait.  Cette page vous permet de créer et de gérer les cas d'assistance associés à votre compte NSS et à votre entreprise.
* Lorsque vous accédez à Digital Advisor dans la console, vous êtes invité à vous connecter à Digital Advisor en saisissant vos informations d'identification NSS.


Notez les points suivants concernant le compte NSS associé à votre connexion :

* Le compte est géré au niveau de l'utilisateur, ce qui signifie qu'il n'est pas visible par les autres utilisateurs qui se connectent.
* Il ne peut y avoir qu'un seul compte NSS associé à Digital Advisor et à la gestion des cas d'assistance, par utilisateur.
* Si vous essayez d'associer un compte de site de support NetApp à un système Cloud Volumes ONTAP , vous ne pouvez choisir que parmi les comptes NSS qui ont été ajoutés à l'organisation dont vous êtes membre.
+
Les informations d'identification au niveau du compte NSS sont différentes du compte NSS associé à votre connexion.  Les informations d'identification au niveau du compte NSS vous permettent de déployer Cloud Volumes ONTAP avec BYOL, d'enregistrer les systèmes PAYGO et de mettre à niveau son logiciel.

+
link:task-adding-nss-accounts.html["En savoir plus sur l'utilisation des informations d'identification NSS avec votre organisation ou votre compte NetApp Console"] .





== Gérez vos identifiants d'utilisateur

Gérez vos informations d'identification utilisateur en mettant à jour le nom d'utilisateur et le mot de passe ou en supprimant les informations d'identification.

.Étapes
. Sélectionnez *Administration > Informations d'identification*.
. Sélectionnez *Informations d'identification de l'utilisateur*.
. Si vous ne disposez pas encore d'informations d'identification utilisateur, vous pouvez sélectionner *Ajouter des informations d'identification NSS* pour ajouter votre compte de site de support NetApp .
. Gérez les informations d’identification existantes en choisissant les options suivantes dans le menu Actions :
+
** *Mettre à jour les informations d'identification* : Mettez à jour le nom d'utilisateur et le mot de passe du compte.
** *Supprimer les informations d'identification* : supprimez le compte NSS associé à votre connexion à la console.



