= 
:allow-uri-read: 


Après avoir installé et configuré l’agent de console, ajoutez vos informations d’identification cloud afin que l’agent de console dispose des autorisations requises pour effectuer des actions dans AWS ou Azure.

[role="tabbed-block"]
====
.AWS
--
.Avant de commencer
Si vous venez de créer ces informations d'identification AWS, leur disponibilité peut prendre quelques minutes.  Attendez quelques minutes avant d’ajouter les informations d’identification à la console.

.Étapes
. Sélectionnez *Administration > Informations d'identification*.
. Sélectionnez *Informations d'identification de l'organisation*.
. Sélectionnez *Ajouter des informations d’identification* et suivez les étapes de l’assistant.
+
.. *Emplacement des informations d'identification* : sélectionnez *Amazon Web Services > Agent.
.. *Définir les informations d'identification* : saisissez une clé d'accès AWS et une clé secrète.
.. *Abonnement Marketplace* : Associez un abonnement Marketplace à ces informations d'identification en vous abonnant maintenant ou en sélectionnant un abonnement existant.
.. *Révision* : Confirmez les détails des nouvelles informations d'identification et sélectionnez *Ajouter*.




Vous pouvez désormais accéder à la https://console.netapp.com["NetApp Console"^] pour commencer à utiliser l'agent de console.

--
.Azuré
--
.Avant de commencer
Si vous venez de créer ces informations d’identification Azure, leur disponibilité peut prendre quelques minutes.  Attendez quelques minutes avant d’ajouter les informations d’identification de l’agent de la console.

.Étapes
. Sélectionnez *Administration > Informations d'identification*.
. Sélectionnez *Ajouter des informations d’identification* et suivez les étapes de l’assistant.
+
.. *Emplacement des informations d'identification* : sélectionnez *Microsoft Azure > Agent*.
.. *Définir les informations d'identification* : saisissez les informations sur le principal du service Microsoft Entra qui accorde les autorisations requises :
+
*** ID de l'application (client)
*** ID du répertoire (locataire)
*** Secret client


.. *Abonnement Marketplace* : Associez un abonnement Marketplace à ces informations d'identification en vous abonnant maintenant ou en sélectionnant un abonnement existant.
.. *Révision* : Confirmez les détails des nouvelles informations d'identification et sélectionnez *Ajouter*.




.Résultat
L’agent de console dispose désormais des autorisations nécessaires pour effectuer des actions dans Azure en votre nom.  Vous pouvez désormais accéder à la https://console.netapp.com["NetApp Console"^] pour commencer à utiliser l'agent de console.

--
====