= 
:allow-uri-read: 


Créez un rôle et appliquez-le à un compte de service que vous utiliserez pour l’instance de machine virtuelle de l’agent de console.

.Étapes
. Créer un rôle personnalisé dans Google Cloud :
+
.. Créez un fichier YAML qui inclut les autorisations définies dans lelink:reference-permissions-gcp.html["Politique de l'agent de console pour Google Cloud"] .
.. Depuis Google Cloud, activez Cloud Shell.
.. Téléchargez le fichier YAML qui inclut les autorisations requises pour l’agent de la console.
.. Créez un rôle personnalisé en utilisant le `gcloud iam roles create` commande.
+
L'exemple suivant crée un rôle nommé « connecteur » au niveau du projet :

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documentation Google Cloud : Création et gestion de rôles personnalisés"^]



. Créer un compte de service dans Google Cloud :
+
.. Depuis le service IAM & Admin, sélectionnez *Comptes de service > Créer un compte de service*.
.. Saisissez les détails du compte de service et sélectionnez *Créer et continuer*.
.. Sélectionnez le rôle que vous venez de créer.
.. Terminez les étapes restantes pour créer le rôle.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documentation Google Cloud : Création d'un compte de service"^]





.Résultat
Vous disposez désormais d’un compte de service que vous pouvez attribuer à l’instance de machine virtuelle de l’agent de console.
