= 
:allow-uri-read: 


.Avant de commencer
Vous devriez avoir les éléments suivants :

* Privilèges root pour installer l'agent de la console.
* Détails sur un serveur proxy, si un proxy est requis pour l'accès Internet à partir de l'agent de la console.
+
Vous avez la possibilité de configurer un serveur proxy après l'installation, mais cela nécessite le redémarrage de l'agent Console.

* Un certificat signé par une autorité de certification, si le serveur proxy utilise HTTPS ou si le proxy est un proxy d'interception.



NOTE: Vous ne pouvez pas définir de certificat pour un serveur proxy transparent lors de l'installation manuelle de l'agent de console. Si vous devez définir un certificat pour un serveur proxy transparent, vous devez utiliser la console de maintenance après l'installation. En savoir plus sur lelink:reference-agent-maint-console-proxy.html["Console de maintenance des agents"] .

.À propos de cette tâche
Après l'installation, l'agent de la console se met automatiquement à jour si une nouvelle version est disponible.

.Étapes
. Si les variables système _http_proxy_ ou _https_proxy_ sont définies sur l'hôte, supprimez-les :
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Si vous ne supprimez pas ces variables système, l'installation échoue.

. Téléchargez le logiciel agent Console puis copiez-le sur l'hôte Linux.  Vous pouvez le télécharger soit depuis la NetApp Console , soit depuis le site d'assistance NetApp .
+
** NetApp Console : Accédez à *Agents > Gestion > Déployer l’agent > Sur site > Installation manuelle*.
+
Choisissez de télécharger les fichiers d'installation de l'agent ou de copier une URL vers les fichiers.



+

NOTE: Téléchargez le programme d'installation de l'agent « online » conçu pour une utilisation sur votre réseau ou dans le cloud. Un programme d'installation « offline » distinct est disponible pour l'agent Console, mais il n'est pris en charge qu'avec les déploiements en mode privé.

+
** NetApp Support Site (nécessaire si vous n'avez pas déjà accès à la Console) https://mysupport.netapp.com/site/products/all/details/netapp-console/downloads-tab["Site de support NetApp"^].


. Attribuer des autorisations pour exécuter le script.
+
[source, cli]
----
chmod +x NetApp_Console_Agent_Cloud_<version>
----
+
Où <version> est la version de l’agent de console que vous avez téléchargé.

. Si vous effectuez l'installation dans un environnement Government Cloud, désactivez les vérifications de configuration.link:task-troubleshoot-agent.html#disable-config-check["Découvrez comment désactiver les vérifications de configuration pour les installations manuelles."]
. Exécutez le script d'installation.
+
[source, cli]
----
./NetApp_Console_Agent_Cloud_<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Vous devrez ajouter les informations de proxy si votre réseau nécessite un proxy pour accéder à Internet. Vous pouvez ajouter un proxy explicite lors de l'installation. Les `--proxy` et `--cacert` paramètres sont facultatifs et il ne vous sera pas demandé de les ajouter. Si vous avez un serveur proxy explicite, vous devrez saisir les paramètres comme indiqué.




NOTE: Si vous souhaitez configurer un proxy transparent, vous pouvez le faire après avoir installé un agent. link:reference-agent-maint-console-proxy.html["Découvrez la console de maintenance des agents"].

+

Voici un exemple de configuration d'un serveur proxy explicite avec un certificat signé par une autorité de certification :

+

[source, cli]
----
./NetApp_Console_Agent_Cloud_v4.0.0 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
`--proxy` configure l'agent de la Console pour utiliser un serveur proxy HTTP ou HTTPS en utilisant l'un des formats suivants :

+ * \http://adresse:port * \http://nom-utilisateur:mot-de-passe@adresse:port * \http://nom-de-domaine%92nom-utilisateur:mot-de-passe@adresse:port * \https://adresse:port * \https://nom-utilisateur:mot-de-passe@adresse:port * \https://nom-de-domaine%92nom-utilisateur:mot-de-passe@adresse:port

+ Notez ce qui suit :

+ ** L'utilisateur peut être un utilisateur local ou un utilisateur de domaine. ** Pour un utilisateur de domaine, vous devez utiliser le code ASCII pour une \ comme indiqué ci-dessus. ** L'agent Console ne prend pas en charge les noms d'utilisateur ni les mots de passe qui incluent le caractère @. ** Si le mot de passe inclut l'un des caractères spéciaux suivants, vous devez échapper ce caractère spécial en le faisant précéder d'une barre oblique inverse : & ou !

+ Par exemple :

+ \http://bxpproxyuser:netapp1\!@address:3128

. Si vous avez utilisé Podman, vous devrez ajuster le port aardvark-dns.
+
.. Connectez-vous en SSH à la machine virtuelle de l'agent de console.
.. Ouvrez le fichier podman _/usr/share/containers/containers.conf_ et modifiez le port choisi pour le service DNS Aardvark.  Par exemple, changez-le en 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
----
+
Par exemple:

+
[source, text]
----
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
----
.. Redémarrez la machine virtuelle de l’agent de console.




. Attendez que l'installation soit terminée.
+
À la fin de l'installation, le service de l'agent de console (occm) redémarre deux fois si vous avez spécifié un serveur proxy.




NOTE: Si l'installation échoue, vous pouvez consulter le rapport d'installation et les journaux pour vous aider à résoudre les problèmes.link:task-troubleshoot-agent.html#troubleshoot-installation["Découvrez comment résoudre les problèmes d’installation."]

. Ouvrez un navigateur Web à partir d’un hôte disposant d’une connexion à la machine virtuelle de l’agent de console et entrez l’URL suivante :
+
https://_ipaddress_[]

. Après vous être connecté, configurez l’agent de la console :
+
.. Spécifiez l’organisation à associer à l’agent de la console.
.. Entrez un nom pour le système.
.. Sous *Exécutez-vous dans un environnement sécurisé ?*, gardez le mode restreint désactivé.
+
Vous devez garder le mode restreint désactivé car ces étapes décrivent comment utiliser la console en mode standard.  Vous devez activer le mode restreint uniquement si vous disposez d'un environnement sécurisé et souhaitez déconnecter ce compte des services backend.  Si c'est le cas,link:task-quick-start-restricted-mode.html["suivez les étapes pour démarrer avec la NetApp Console en mode restreint"] .

.. Sélectionnez *Commençons*.



