= 
:allow-uri-read: 


Selon votre système d'exploitation, Podman ou Docker Engine est requis avant l'installation de l'agent.

* Podman est requis pour Red Hat Enterprise Linux 8 et 9.
+
<<podman-versions,Afficher les versions de Podman prises en charge>> .

* Docker Engine est requis pour Ubuntu.
+
<<podman-versions,Afficher les versions de Docker Engine prises en charge>> .



.Étapes
[role="tabbed-block"]
====
.Podman
--
Installez et configurez Podman :

* Activer et démarrer le service podman.socket
* Installer Python 3
* Installez le package podman-compose correspondant
* Ajoutez podman-compose à la variable d'environnement PATH
* Vérifiez que votre version de Podman utilise Netavark Aardvark DNS au lieu de CNI.



NOTE: Ajustez le port aardvark-dns (par défaut : 53) après l’installation de l’agent pour éviter les conflits de port DNS.  Suivez les instructions pour configurer le port.

.Étapes
. Supprimez le package podman-docker s'il est installé sur l'hôte.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Installez Podman.
+
Téléchargez Podman depuis les dépôts Red Hat Enterprise Linux.

+
Pour Red Hat Enterprise Linux 9 :

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
Où <version> est la version prise en charge de Podman que vous installez. <<podman-versions,Afficher les versions de Podman prises en charge>> .

+
Pour Red Hat Enterprise Linux 8 :

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
Où <version> est la version prise en charge de Podman que vous installez. <<podman-versions,Afficher les versions de Podman prises en charge>> .

. Activez et démarrez le service podman.socket.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. Installez python3.
+
[source, cli]
----
sudo dnf install python3
----
. Installez EPEL pour obtenir podman-compose.
+
.. Si vous utilisez Red Hat Enterprise 9.1 à 9.6 :
+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----


. Installez le package podman-compose 1.5.0.
+
[source, cli]
----
sudo dnf install podman-compose-1.5.0
----
+
.. Si vous utilisez Red Hat Enterprise Linux 8 :
+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----


. Installez le package podman-compose 1.0.6.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: En utilisant le `dnf install` la commande répond à l'exigence d'ajout de podman-compose à la variable d'environnement PATH.  La commande d'installation ajoute podman-compose à /usr/bin, qui est déjà inclus dans le `secure_path` option sur l'hôte.

. Si vous utilisez Red Hat Enterprise Linux 8, vérifiez que votre version Podman utilise NetAvark avec Aardvark DNS au lieu de CNI.
+
.. Vérifiez si votre networkBackend est défini sur CNI en exécutant la commande suivante :




[listing]
----
podman info | grep networkBackend
----
. Si le networkBackend est défini sur `CNI` , vous devrez le changer en `netavark` .
. Installer `netavark` et `aardvark-dns` en utilisant la commande suivante :


[listing]
----
dnf install aardvark-dns netavark
----
. Ouvrez le `/etc/containers/containers.conf` fichier et modifiez l'option network_backend pour utiliser « netavark » au lieu de « cni ».
+
Si `/etc/containers/containers.conf` n'existe pas, effectuez les modifications de configuration pour `/usr/share/containers/containers.conf` .

+
.. Redémarrez podman.




[listing]
----
systemctl restart podman
----
. Confirmez que networkBackend est désormais modifié en « netavark » à l'aide de la commande suivante :


[listing]
----
podman info | grep networkBackend
----
--
.Moteur Docker
--
Suivez la documentation de Docker pour installer Docker Engine.

.Étapes
. https://docs.docker.com/engine/install/["Afficher les instructions d'installation depuis Docker"^]
+
Installez une version compatible de Docker Engine en suivant les étapes suivantes. N’installez pas la dernière version, car la console ne la prend pas en charge.

. Vérifiez que Docker est activé et en cours d’exécution.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====